### ISSUE TITLE
Generate navigation menu fails to list available commands in version 10.0.0

### ISSUE THREAD

**Issue by ctaleck** [nrwl/nx-console#923] opened 2020-01-02 15:18 UTC
Angular console version _10.0.0_ disabled the **Generate** menu item and does not display the command palette for my project. When I downgrade to version _9.1.1_, the command works by displaying the list of commands. 

I have the `angular.json` and `nx.json` files in my workspace. I do not have the new `workspace.json` file.

**Comment by StevenWouters** [comment] 2020-01-03 12:28
I have the same problem. 

stack trace: TypeError: Cannot convert undefined or null to object	at Function.entries (<anonymous>)	at readCollectionSchematics (c:\foldername\nrwl.angular-console-10.0.0\main.js:167374:12)	at readCollection (c:\foldername\nrwl.angular-console-10.0.0\main.js:167363:16)

**Comment by KingDarBoja** [comment] 2020-01-09 19:57
I get the same issue, the **generate** option doesn't display tje cpmmand palette.

More info:
```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by AlbertoD94** [comment] 2020-01-10 13:10
Same

**Comment by alejandrogkl** [comment] 2020-01-30 14:58
Same here, when downgrade to 9.1.1 the generate command palette works

**Comment by Jejuni** [comment] 2020-02-10 14:20
I've got the same error :
`[[object Object]]Cannot convert undefined or null to object`

`Cannot convert undefined or null to object
	at Function.entries (<anonymous>)
	at readCollectionSchematics (c:\Users\Jejun\.vscode\extensions\nrwl.angular-console-10.0.0\main.js:167374:12)
	at readCollection(...)`

I've narrowed it down to the suite of Telerik products we have installed.
After further inspection some packages in the node_modules/@progress folder cause the issues.
Among them was, for instance, `kendo-angular-l10n`.

This package, unlike most others, did not have a `schematics` folder. However, in the included package.json there were 2 entries referencing the schematics: 
`(...)
"schematics": "./schematics/collection.json",
  "files": [
    "dist",
    "schematics"
  ]
(...)`

Removing these entries fixed the problem.
However, after reinstalling or updating the package.json will be regenerated and the problem starts appearing again.
Could this be fixed so a non-existing schematics entry/folder doesn't cause the crash?

**Comment by alejandrogkl** [comment] 2020-02-10 14:29
same scenario here, i even report the issue to telerik and they refer to this issue.  until the issue is solved i am using v9.1.1

**Comment by Jejuni** [comment] 2020-02-10 14:36
> same scenario here, i even report the issue to telerik and they refer to this issue. until the issue is solved i am using v9.1.1

It's true that the tool shouldn't be crashing because of a null/undefined issue and handle it more gracefully. But it's also true that the Telerik package.json references non-existing folders. You'd hope that Telerik would also be on the issue and try to fix it...

**Comment by ctaleck** [comment] 2020-02-17 20:40
You are on to something @Jejuni. My project also imports **@progress** dependencies when I reported this issue. 

Indeed, when I opened another _Nx worksapce_ without **@progress** dependencies using **Nx Console version 10.0.0**, I was able to see the _Generate_ command palette.

**Comment by JavikusRod** [comment] 2020-03-12 16:05
Any solution?

**Comment by SirajB** [comment] 2020-07-08 16:37
Same issue here, I've rolled back to 9.1.1 and it still won't work

**Comment by Jejuni** [comment] 2020-07-08 17:58
The issue seems to still be present even in the latest version.
I've since written a little script that fixes the issue. It sucks that this is necessary at all, but it is what it is.
The script simply reads in the package.json of the offending packages and removes the erroneous entries.

``` js
const fs = require('fs');
const path = require('path');

function readFile(file) {
  return new Promise((resolve, reject) => {
    fs.readFile(file, {}, (err, content) => {
      if (err) {
        reject(err);
      } else {
        resolve(content);
      }
    });
  });
}

function writeFile(file, content) {
  return new Promise((resolve, reject) => {
    fs.writeFile(file, content, (err) => {
      if (err) {
        reject(err);
      } else {
        resolve();
      }
    });
  });
}

(async function () {
  console.log('Fixing Telerik/Progress packages erroneous schematics entries');

  const knownBadPackages = ['kendo-angular-l10n', 'kendo-angular-intl', 'kendo-angular-common'];
  const knownBackPackagesJsonFiles = knownBadPackages.map((bp) => path.join(__dirname, '..', `node_modules/@progress/${bp}/package.json`));
  const knownBadPackaesContentPromises = knownBackPackagesJsonFiles.map((bp) => readFile(bp).then((res) => ({ packagePath: bp, result: JSON.parse(res) })));
  /** @type Array<{ packagePath: string, result: string }>*/
  const badPackagesFileContent = await Promise.all(knownBadPackaesContentPromises);

  for ({ packagePath, result } of badPackagesFileContent) {
    delete result.schematics;
    await writeFile(packagePath, JSON.stringify(result, null, 3));
  }

  console.log('Successfully fixed Telerik/Progress packages');
})();

```

The `const knownBadPackages` array includes the packages I know of and use that need fixing. If you find more, simply add to the list. 
To use the script, simply make a folder called (for instance) `scripts` at the same level you have your package.json and node_modules.

Then in your package.json add, under scripts:
```
"telerik-fix-postinstall": "node ./scripts/fixProgressPackages.js",
```
Then, in your package.json, find the "postinstall" script and add
```
&& npm run telerik-fix-postinstall
```

After that simply run `npm install` and the fix should be applied.
Since it's in your postinstall this fix will also be applied for all your coworkers and on fresh installs as well.

**Comment by weijinhua** [comment] 2020-07-09 02:42
@Jejuni  the script is working for me. thanks.

**Comment by SirajB** [comment] 2020-07-09 10:59
I don't have those packages that you do @Jejuni , in fact the error I get does not point to any specific folder at all: 'Command 'nx: generate' resulted in an error (Cannot convert undefined or null to object)'

It works in another repo I have just not the one I am currently working in

**Comment by Jejuni** [comment] 2020-07-09 11:16
@SirajB The error sadly doesn't point to a specific folder. I just found those packages by trial and error by individually uninstalling things from my package.json. There's a chance that some other packages you're using are exhibiting the same problem as the telerik packages. You might want to narrow it down to those packages and then adapt my script.

**Comment by SirajB** [comment] 2020-07-09 17:59
My issue was slightly seperate but still related, npm audit was needed in order to fix my modules and then everything worked again!

**Comment by SirajB** [comment] 2020-07-09 17:59
My issue was slightly seperate but still related, npm audit was needed in order to fix my modules and then everything worked again!

**Comment by SirajB** [comment] 2020-07-17 09:22
Never mind the issue has arisen again and now it won't be fixed....any news on this?

**Comment by ZenSoftware** [comment] 2020-07-25 07:33
Unfortunately this is still occurring as of Nx Console v13 in my project using Telerik packages.  Fortunately downgrading to Nx Console v9.1.1 still works.

**Comment by ianvink** [comment] 2020-09-04 20:33
I had to add basically everything, run npm install, then restart VS code. Then it worked

  const knownBadPackages = [
    'kendo-angular-l10n',
    'kendo-angular-intl',
    'kendo-angular-common',
    'kendo-angular-buttons',
    'kendo-angular-dialog',
    'kendo-angular-dropdowns',
    'kendo-angular-editor',
    'kendo-angular-inputs',
    'kendo-angular-layout',
    'kendo-angular-popup',
    'kendo-angular-toolbar',
    'kendo-angular-upload',
    'kendo-drawing',
    'kendo-theme-default',
  ];

**Comment by ianvink** [comment] 2020-09-16 21:11
NX Console is wonderful.

Last night Kendo updated to a new version and NX Console stopped again. I deleted node_modules, restarted VS, then ran npm install.

The fix js above is working again

**Comment by ctaleck** [comment] 2020-10-09 20:53
If someone tests PR #971 and sees that it fixes this issue, please close it. Thanks.

**Comment by sandikbarr** [comment] 2021-03-12 22:35
Verified #971 does handle this issue and reports the error along with `Invalid package.json for schematic ${collectionName}` in the dev tools console. Invalid schematics are not listed in the dropdown.

**Closed by sandikbarr** 2021-03-12 22:35 UTC
Labels: bug
