### ISSUE TITLE
VSCode: angular.json 'Go to "project" configuration' when higher in subtree

### ISSUE THREAD

**Issue by TomONeill** [nrwl/nx-console#1253] opened 2022-02-21 12:47 UTC
Hi, I've loaded my project in VSCode from a higher level than the project's root.

Let's say this is my simplified folder structure:
`C:\SC\my-project\project\<angular>`
`C:\SC\my-project\pipeline\`
I've got the following folder loaded into my VSCode:
`C:\SC\my-project`

Clicking on the `Go to "project" configuration` link results in a popup in the bottom right corner:
`Unable to open 'project.json': File not found.`
With a buttton to create the file. Clicking on it creates an empty `project.json` file in `\apps` instead of `\my-project\apps`.

Is it possible to get this fixed so it doesn't matter where you load the project from?

**Comment by TomONeill** [comment] 2022-02-22 15:14
The file structure you mention is correct. It's an Nx workspace.

**Comment by ZackDeRose** [comment] 2022-02-22 15:48
Got it - can reproduce. Looks like our pathing is upset in the case you're describing.

**Comment by ZackDeRose** [comment] 2022-02-22 16:19
@TomONeill can you verify that you're using v17.14.1 of Nx Console?

(And if not can you upgrade to that version and confirm you're still seeing it?)

Upgrading to latest fixed this for me.

**Comment by ZackDeRose** [comment] 2022-02-22 16:23
Unfortunate. I'll see if I can reproduce on 17.14.1 on a windows machine.

**Comment by ZackDeRose** [comment] 2022-02-25 17:38
Hey @TomONeill - I was unable to reproduce after getting my hands on a Windows 10 machine.

I did see the issue initially, but after clicking on the "Change Workspace" option inside of "Generate & Run Target" to set the root, the issue no longer was present. Can you confirm that this is still an issue for you?

**Comment by TomONeill** [comment] 2022-03-02 09:57
Hey @ZackDeRose,

Thanks, that resolved my issue. I had hidden the NX Console on the left side and never saw that option.

**Comment by ZackDeRose** [comment] 2022-03-08 18:23
Glad this got solved for you @TomONeill. Closing it out.

**Closed by ZackDeRose** 2022-03-08 18:23 UTC
Labels: type: bug
