### ISSUE TITLE
Nx console (Jetbrains) create nx-win32-x64-msvc file

### ISSUE THREAD

**Issue by puschie286** [nrwl/nx-console#1950] opened 2023-11-29 15:21 UTC
### Current Behavior

Nx Console create a 'nx.win32-x64-msvc.node' file in every project and locks it. makes impossible to delete node_modules, update / install with yarn or npm.

### Expected Behavior

dont create locked file - dont create any files in non nx projects!

### Steps to Reproduce

1. open any project with an jebrains ide (with NxConsole installed) that have a node_modules folder
2. try to delete node_modules

### Nx Report

```shell
nx is not installed
```

### Failure Logs

```shell
yarn install ->
error Error: EPERM: operation not permitted, unlink '***\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node'
```

### Package Manager Version

yarn 1.22.21

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

occur in nx based projects and non nx projects

**Comment by MaxKless** [comment] 2023-12-04 09:48
Closing this as a duplicate of https://github.com/nrwl/nx-console/issues/1863 

The daemon is locking the file when nx is starting up, probably because you have nx somewhere in your dependency chain. Maybe `angular-eslint`? 
We're working on a fix as specified in the linked issue. 
For now you can run `npx nx daemon --stop` before deleting node_modules

**Closed by MaxKless** 2023-12-04 09:48 UTC
Labels: type: bug
