### ISSUE TITLE
Command `npm ci` not working when IDE is opened

### ISSUE THREAD

**Issue by 3htomit** [nrwl/nx-console#2026] opened 2024-02-19 12:54 UTC
## Current Behavior

When Webstorm is opened, if I run the `npm ci` command it fails with the error message below. I therefore need to stop the IDE and kill the task 'Node.js JS Runtime' so the `npm ci` runs correctly.
The other solution is to uninstall the NX Console plugin from Webstorm and then I can run the `npm ci` with the IDE opened.

Here are the error details from my terminal :
![image](https://github.com/nrwl/nx-console/assets/97245071/c53506df-9f15-4a15-b4e3-cee7e8a6504d)

Here is the log I get :
[2024-02-19T10_25_54_362Z-debug-0.log](https://github.com/nrwl/nx-console/files/14329864/2024-02-19T10_25_54_362Z-debug-0.log)

## Expected Behavior

I expect to be able to run the `npm ci` command even if Webstorm is opened with NX Console plugin installed.

## Steps to Reproduce

- Open Webstorm with NX Console plugin installed
- Run `npm ci` command in a terminal
- Then you should get the error I got (see screenshot above)
- Close the IDE
- Then you should see a 'Node.js JS Runtime' task to pop in your task manager

### Environment

Webstorm : 2023.3.4
NX : 17.2.8
NX Console : 1.18.0

```javascript
"devDependencies": {
    "@angular-devkit/build-angular": "17.0.8",
    "@angular-devkit/core": "17.0.8",
    "@angular-devkit/schematics": "17.0.8",
    "@angular-eslint/builder": "17.1.1",
    "@angular-eslint/eslint-plugin": "17.1.1",
    "@angular-eslint/eslint-plugin-template": "17.1.1",
    "@angular-eslint/schematics": "17.1.1",
    "@angular-eslint/template-parser": "17.1.1",
    "@angular/cli": "~17.0.8",
    "@angular/compiler-cli": "17.0.8",
    "@angular/language-service": "17.0.8",
    "@hirez_io/observer-spy": "^2.2.0",
    "@lucca/proxy": "^4.3.0",
    "@ngneat/spectator": "16.0.0",
    "@nx/angular": "17.2.8",
    "@nx/eslint": "17.2.8",
    "@nx/eslint-plugin": "17.2.8",
    "@nx/jest": "17.2.8",
    "@nx/js": "17.2.8",
    "@nx/workspace": "17.2.8",
    "@schematics/angular": "17.0.8",
    "@swc-node/register": "~1.6.8",
    "@swc/core": "~1.3.107",
    "@types/eslint": "^8.56.2",
    "@types/jest": "^29.5.12",
    "@types/node": "18.16.9",
    "@typescript-eslint/eslint-plugin": "^6.17.0",
    "@typescript-eslint/parser": "^6.17.0",
    "@typescript-eslint/utils": "^6.17.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^5.1.3",
    "husky": "^8.0.3",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-preset-angular": "13.1.6",
    "jsonc-eslint-parser": "^2.4.0",
    "lint-staged": "^15.2.2",
    "ng-mocks": "^14.12.1",
    "nx": "17.2.8",
    "prettier": "^3.1.1",
    "stylelint": "^14.16.1",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-prettier": "^2.0.0",
    "ts-jest": "^29.1.2",
    "ts-mockito": "^2.6.1",
    "ts-node": "^10.9.2",
    "typescript": "5.2.2",
    "webpack-bundle-analyzer": "^4.10.1"
  },
```

**Comment by MaxKless** [comment] 2024-02-26 11:46
This is a known issue and I will implement a solution in nx core soon. For now you can run `npx nx reset` or `npx nx daemon --stop` as a workaround. 
Closing as duplicate of https://github.com/nrwl/nx-console/issues/1863

**Closed as completed by MaxKless** 2024-02-26 11:46 UTC
Labels: type: bug
