### ISSUE TITLE
Errors after running npx add-nx-to-monorepo

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx-console#1202] opened 2021-12-19 18:19 UTC
I cloned the React repository, which is a yarn workspace, and ran `npx add-nx-to-monorepo`.  When I opened Nx Console, and clicked the `build` generator, I get the following error:

```
TypeError: Cannot read property 'getWorkspacePath' of undefined
```

I think there was an error when I first opened the extension:

```
Nx Console encountered an error when activating
{}
```

## After Nx 13.3.11
* Cannot view targets for projects 
* edit workspace definition should go to package.json instead of project or workspace.json

**Comment by Cammisuli** [comment] 2021-12-20 02:20
The underlying issue looks to be coming from Nx itself. I'll try and reach out to someone on the team on that part. 

But to actually show the issue on console itself is lost. I'll fix that to show the errors properly. 

But the error itself is as follows:
```
Error: 
	at buildWorkspaceConfigurationFromGlobs (/Users/jon/Dev/react/node_modules/@nrwl/tao/src/shared/workspace.js:399:23)
	at Workspaces.readWorkspaceConfiguration (/Users/jon/Dev/react/node_modules/@nrwl/tao/src/shared/workspace.js:57:15)
	at Object.readWorkspaceConfig (/Users/jon/Dev/react/node_modules/@nrwl/workspace/src/core/file-utils.js:138:21)
	at getNxWorkspaceConfig (/Users/jon/Dev/nx-console/dist/apps/vscode/main.js:218076:52)
```

**Comment by Cammisuli** [comment] 2021-12-20 14:59
The underlying issue was resolved with Nx 13.3.11, but I'm going to keep this open to track the issues I saw with the react repo.

**Comment by zambov** [comment] 2021-12-21 08:37
Hi,

I've encountered the same problem @Cammisuli mentioned, there's no apparently reason that causes the problem. The outpu log says:

`
Nx Console encountered an error when activating
{}
TypeError: Cannot read property 'getWorkspacePath' of undefined
`

Maybe could be caused by a vscode update?

**Comment by slightHYP** [comment] 2021-12-21 10:46
It seems to be related to #1197

**Closed** 2022-06-03 20:47 UTC
Labels: type: bug
