### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nagendra-pujari** [nrwl/nx-console#1745] opened 2023-05-23 06:36 UTC
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `18.1.1`
- OS Version: `Linux x64 5.4.0-109-generic`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by flowg** [comment] 2023-05-23 15:07
Hello 👋 I guess it's somewhat related so I'll just put it there.
I just found out why my Webstorm 2023.1.2, `Build #WS-231.9011.35, built on May 16, 2023`, was freezing these past couple days every time I was left-clicking on a folder in the project View : apparently it's due to the Nx Console v1.4.0, that is installed in my IDE.

I'm on a MacBook Pro, with Apple M1 Max, 32 Go RAM, and MacOS Ventura 13.4 .

When I disable this plugin, the IDE works as usual. When I enable it, it bugs the way I described before.

Nx Console v1.4.0 apparently has been there for a month and it never caused any problem.

But recently, I just migrated my project to Nx 16 and Angular 16 and voilà !

Do you think it might be related ? 🤔

**Comment by MaxKless** [comment] 2023-05-24 09:03
Thanks for the reports :) 
We've heard of some freezing issues in Nx 16 before, might be related. Is there any way you can provide a cpu profile or something similar for IntelliJ too?

**Comment by StringKe** [comment] 2023-06-07 07:04
I'm having the same problem, but I don't know what the trigger conditions are. I occasionally encounter this problem when I right click on a file and can only force quit.

**Comment by flowg** [comment] 2023-06-08 08:50
Hi 👋
@MaxKless  I'm sorry but I don't know how to do that... 😕
If you know of a link I can consult with the manip to do it, I'll be happy to try ☺️

**Comment by flowg** [comment] 2023-06-08 08:54
So far I can confirm you that I still have this issue with the new Nx Console v1.5.0 🤷🏻‍♂️

**Comment by MaxKless** [comment] 2023-06-08 10:33
Ah too bad! It would be great if you could try and run a profile for me because I can't repro it for JetBrains. 
You can clone the `nx-console` repo, run `yarn install` and then in the top right run `runIde` with the profiler attached (see screenshot). Maybe there will be some helpful information...

<img width="454" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/79c69402-1ad3-4cb8-99d0-556a336df201">

**Comment by MaxKless** [comment] 2023-06-08 10:34
Hey @nagendra-pujari can you attach the CPU profile too? I'm just seeing the file name in the issue :)

**Comment by MaxKless** [comment] 2023-07-21 13:54
@flowg @StringKe your issues should be fixed in the latest Nx Console versions.
We removed a lot of these calls that would block the UI in https://github.com/nrwl/nx-console/pull/1816 https://github.com/nrwl/nx-console/pull/1809 and more.
If you continue seeing these issues in the latest version, please let me know or create a new issue! But it shouldn't happen anymore.

@nagendra-pujari since you haven't responded since the original issue, I'll close this for now. If you have a repro or more info, feel free to respond and I can reopen the issue.

**Closed by MaxKless** 2023-07-21 13:54 UTC

**Comment by dben89x** [comment] 2024-03-25 19:01
I'd just like to add another report of nx-console eating up a ton of memory and battery in Webstorm. Running on very capable hardware: Macbook Pro, M1 Max, 64 GB, Sonoma. As soon as I installed nx-console on Webstorm I started noticing my battery draining 30% in a half hour and my laptop getting hot, which it never does. I took a look at Activity Monitor and noticed a watcher process started by nx-console eating up all my RAM. So I disabled the plugin, and now 5 minutes later my computer has cooled down significantly. Any diagnostic info I can provide that might be helpful?

**Comment by MaxKless** [comment] 2024-03-26 09:26
Yes, if you could you provide some logs that would help.
Go to `Help` > `Diagnostic Tools` > `Debug Log Settings.`.. and then insert `#dev.nx.console:trace`. Then paste the `idea.log` or sections of it when the error happens.

Also the `daemon.log` & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`
Also, please provide your `nx report` so we can see which watcher logic is being used. 

It could be that something is up causing the watcher to constantly retrigger which will constantly recalculate the project graph and can be work-intensive.

**Comment by MaxKless** [comment] 2024-03-26 09:27
ideally, create a new issue with these details so this issue doesn't become diluted & confusing

**Comment by fjanicki** [comment] 2024-04-22 18:53
I'm experiencing the same issue. 150% cpu per open project just for the nx watcher.

**Comment by MaxKless** [comment] 2024-05-03 12:14
Hey! Can you try on the latest version? :) I made some changes that should fix these issues.
If you could report back whether it still happens on `18.21.0`/`1.23.0` that would be amazing!

**Comment by leegunwoo98** [comment] 2024-12-24 06:24
This is happening on 19.8.4
