### ISSUE TITLE
Vscode Generate UI runs outside of WSL.

### ISSUE THREAD

**Issue by JeanMeche** [nrwl/nx-console#1864] opened 2023-08-20 14:33 UTC
## Current Behavior
I have a project opened in VScode but runs in WSL2 (so with the WSL remote extension enabled). 

When attempting to generate a new component, I open the generate UI and I try to create a new component. 

This fails with the following error:  

```
 *  Executing task: npx nx generate @nx/angular:component --name=test --project=master-admin --no-interactive --dry-run 

'\\wsl.localhost\Ubuntu\home\rieglerm\dev\rdg-ui'
CMD.EXE a été démarré avec le chemin d’accès comme répertoire en
cours. Les chemins d’accès UNC ne sont pas prise en charge. Utilisation
du répertoire Windows par défaut.
'nx' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

 *  The terminal process "/bin/bash '-c', 'npx nx generate @nx/angular:component --name=test --project=master-admin --no-interactive --dry-run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

I don't understand why this is run with the CMD.EXE as my default terminal is `bash`. Any idea what's happening ? 

## Expected Behavior

The schematic should run within WSL. 

### Environment

- Nx Console version: v18.6.0
- VSCode version: 1.81.0

**Comment by MaxKless** [comment] 2023-08-21 09:22
Hey @JeanMeche,
thanks for the report. 
I looked into it and on my windows machine, generating something within WSL worked perfectly fine. 

- Can you provide some more information on your setup? 
- If you run something else via the task API (e.g. `Ctrl Shift P -> Tasks: Run Task -> anything from typescript or nx`) do you get the same error? 

I'm a bit confused by the error message since it calls out it doesn't recognize `nx` as a command, even though we run it through npx. 
Also, the process seems to be called `/bin/bash` which is what we would expect in WSL, right? Not sure what's going on here...

**Comment by Cammisuli** [comment] 2023-08-21 11:02
This looks like vscode just opened the wsl folder location from the Windows side. Note the `\\wsl.localhost\Ubuntu\home` path, wsl paths should be `/home/rieglerm/dev/rdg-ui`

You need to tell vscode to reopen to connect inside the wsl instance rather than outside.

**Comment by JeanMeche** [comment] 2023-08-21 11:42
I know very well how to run a project in WSL. I can confirm, VScode is in remote mode. 

There is no issue when I run a typescript task, only with nx tasks.

**Comment by ericjeker** [comment] 2023-09-12 17:07
@MaxKless , you asked me to provide more feedback following my, not very constructive I admit, review on JetBrains website: https://plugins.jetbrains.com/plugin/21060-nx-console/reviews#review=89658-89772

The problem is I don't know how to provide anything to help you because there is no log at all and no error. It just doesn't recognize my project as a Nx workspace.

![image](https://github.com/nrwl/nx-console/assets/979397/bfccf719-0581-4039-a5c5-1e5f715a4720)

I am on Windows, using WSL with a Ubuntu 22. I don't want to code in remote.

Just let me know how I can help.

**Comment by MaxKless** [comment] 2023-09-12 17:23
Interesting, we just merged another WSL fix but this looks like a duplicate of https://github.com/nrwl/nx-console/issues/1876 so I will continue the discussion there

**Comment by MaxKless** [comment] 2023-09-15 15:49
Hey sorry we haven't been able to figure this out yet. Can you reproduce it in the [nx-examples](https://github.com/nrwl/nx-examples) repo?

**Comment by steven10172** [comment] 2023-09-19 06:18
I am exhibiting a similar error, but I can use some of the actions. I can use `generate`, `generate (UI)`, `move`, `remove` commands, but the various run targets all fail with an error similar to this:
```
/home/steven/workspace/nx-monorepo/node_modules/.bin/nx run node-app:build
zsh:cd:1: no such file or directory: //wsl.localhost/Ubuntu/home/steven/workspace/nx-monorepo

Process finished with exit code 1
```

**Comment by MaxKless** [comment] 2023-10-11 08:58
Hey @steven10172 have you tried this on the latest version? We pushed a fix for this in [v1.13.2](https://github.com/nrwl/nx-console/releases/tag/intellij-v1.13.2) so it should work now.

Would be awesome if you could check.

**Comment by JeanMeche** [comment] 2023-10-11 11:59
> Hey sorry we haven't been able to figure this out yet. Can you reproduce it in the [nx-examples](https://github.com/nrwl/nx-examples) repo?

Just saw your message. On the nx-examples repo, clicking on the "Generate" button has no visible effect (no console open or whatsoever).  

Copying the generation command and running in a terminal works without any issue though `nx g @nx/angular:component --name=testest --project=cart --export=true --standalone=true`.

**Comment by MaxKless** [comment] 2023-10-11 12:02
Can you post your `Nx Console Client` & `Nx Console` output logs?

**Comment by MaxKless** [comment] 2023-10-11 13:53
That's weird... and pnpm is installed in WSL as well? Are you running your commands with nx installed globally or npx / pnpx?

**Comment by JeanMeche** [comment] 2023-10-11 14:04
Yes it is global and yes this very weird. 

> $ which nx
> /home/rieglerm/.nvm/versions/node/v16.20.1/bin/nx
> $ which pnpm
> /home/rieglerm/.nvm/versions/node/v16.20.1/bin/pnpm

Is maybe nvm messing with some stuff ?

**Comment by MaxKless** [comment] 2024-04-02 11:25
Hey! Just checking in @JeanMeche. Is this still happening on the latest Nx Console version?
Did you go through the steps under https://nx.dev/recipes/nx-console/console-troubleshooting and see if that helped? Looks like something weird is going on with nvm

**Comment by MaxKless** [comment] 2024-05-06 10:16
Hey! Just want to ping you again and let you know that this is probably an issue with how `nvm` & VSCode work together. It's very common and the https://nx.dev/recipes/nx-console/console-troubleshooting give a good breakdown of how to fix it. 

Most of the time, it's due to a default version being set or node being installed via `homebrew` as well as `nvm`.

I'm closing this issue for now but if it still persists, please let me know and we'll have another look :) Thank you!

**Closed by MaxKless** 2024-05-06 10:16 UTC
Labels: type: bug, os: windows, blocked: more info needed, vscode
