### ISSUE TITLE
VS Code plugin error: Cannot find module 'nx/presets/core.json'

### ISSUE THREAD

**Issue by owen26** [nrwl/nx-console#1416] opened 2022-11-23 10:51 UTC
### Current Behavior

vscode nx plugin failed initialisation

VS code plugin console output

```
[error] Activating extension nrwl.angular-console failed due to an error:
[error] Error: Cannot find module 'nx/presets/core.json'
    at Function.t [as resolve] (/Users/xinan/.vscode/extensions/nrwl.angular-console-17.25.0/main.js:1:882)
    at t.Workspaces.readNxJson (/Users/xinan/.vscode/extensions/nrwl.angular-console-17.25.0/172.js:22:518449)
    at a (/Users/xinan/.vscode/extensions/nrwl.angular-console-17.25.0/172.js:22:509130)
    at Object.56797 (/Users/xinan/.vscode/extensions/nrwl.angular-console-17.25.0/172.js:22:527636)
    at s (/Users/xinan/.vscode/extensions/nrwl.angular-console-17.25.0/main.js:169:39483)
```

### Expected Behavior

no error

### Steps to Reproduce

1. open an NX workspace in vs code
2. switch to NX plugin tab
3. observe a Welcome panel, and empty panel for Generate & Run section
4. open plugin console output
5. observe error messages

### Nx Report

```shell
Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.8.0
   
   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

VS Code plugin version: v17.25.0

**Comment by MaxKless** [comment] 2022-11-25 08:41
Hey @owen26 do you have a repo where I can look at this? You're not the first person to report this but I cant seem to reproduce the issue...

**Comment by MaxKless** [comment] 2022-11-25 10:44
Duplicate of #1405

**Closed by MaxKless** 2022-11-25 10:44 UTC
Labels: type: bug
