### ISSUE TITLE
nx-console operates inconsistent cache

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx-console#2281] opened 2024-10-08 00:36 UTC
nx-console operates inconsistent cache

## Current Behavior

UI for nx-console is iffy and UI renders intermittently or never when workspace changes

## Expected Behavior

nx-console plugin should refresh its cache and be consistent for high velocity development

## Steps to Reproduce

npx create-nx-workspace@latest

create app ADMIN

nx serve ADMIN

launch nx-console using key strokes
UI fails to render

IDE has to be shut down and restarted then UI renders for nx-console (annoying)

### Failure Logs / Images / Videos

2024-10-07 20:35:20,147 [3098514]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-10-07 20:35:20,147 [3098514]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2024-10-07 20:35:20,148 [3098515]   INFO - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 475
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1728347720147000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.5"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.32.1"}},"events":[{"name":"actionTriggered","params":{"engagement_time_msec":"1","session_id":"c9e21528-84e9-4cd1-9f14-a0f4f46bd137","debug_mode":null,"action_type":"generate.ui","source":"command"}}]}
BODY END
2024-10-07 20:35:20,372 [3098739]   INFO - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Security-Policy-Report-Only: script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/scaffolding/ascnsrsggc:51:0
-> Content-Type: text/plain
-> Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to=coop_reporting
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Tue, 08 Oct 2024 00:35:20 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END

### Environment

JetBRAINS 2024.1

nx report

 NX   It's time to update Nx 🎉

Your repository uses a higher version of Nx (20.0.0) than your global CLI version (19.8.4)
For more information, see https://nx.dev/more-concepts/global-nx

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 19.8.4
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nrwl/tao          : 19.8.4
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------

**Comment by nhhockeyplayer** [comment] 2024-10-27 08:01
meanstack02@admin meanstacknh % tail -f ~/Library/Logs/JetBrains/WebStorm2024.1/idea.log | tee idea.output.log
-> Date: Sun, 27 Oct 2024 07:58:24 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-10-27 03:58:39,444 [ 157522]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-10-27 03:58:39,445 [ 157523]   INFO - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 475
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1730015919444000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.5"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.32.2"}},"events":[{"name":"actionTriggered","params":{"engagement_time_msec":"1","session_id":"fe7f740d-6ac5-4e24-b59b-cb43f717f278","debug_mode":null,"action_type":"generate.ui","source":"command"}}]}
BODY END
2024-10-27 03:58:39,604 [ 157682]  FINER - #dev.nx.console.nxls.NxlsWrapper - Error from nxls: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-17" org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at dev.nx.console.nxls.NxlsWrapper.start$lambda$10$lambda$9(NxlsWrapper.kt:110)
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
2024-10-27 03:58:39,605 [ 157683]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-10-27 03:58:39,606 [ 157684]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@574506630), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@104cdf71, Dispatchers.Default]
2024-10-27 03:58:39,673 [ 157751]   INFO - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Security-Policy-Report-Only: script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/scaffolding/ascnsrsggc:51:0
-> Content-Type: text/plain
-> Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to=coop_reporting
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Sun, 27 Oct 2024 07:58:39 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END

**Comment by nhhockeyplayer** [comment] 2024-11-09 18:26
can anyone fix this?

the nx-console UI fails to come up

I have a repo to connect to and see https://github.com/nhhockeyplayer/meanstacknh
just ask to be collaborator and I will grant access as long as your part of NX team

this has gone on for so long
logs have been provided

high velocity development is basically in the breakdown lane

please
requesting prioritized help and attention to this

**Comment by nhhockeyplayer** [comment] 2024-11-09 18:28
here is latest webstorm IDE log

shift-apt-O

```
tail -f ~/Library/Logs/JetBrains/WebStorm2024.1/idea.log | tee idea.output.log
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-11-09 13:23:20,861 [16257373]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:23:20,861 [16257373]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-11-09 13:23:23,542 [16260054]   INFO - #c.i.o.c.i.s.StoreUtil - saveProjectsAndApp took 2681 ms
2024-11-09 13:27:09,337 [16485849]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [meanstacknh]
2024-11-09 13:27:09,343 [16485855]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@57d0419f (reason: Push on VFS changes)
2024-11-09 13:27:09,345 [16485857]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@57d0419f (reason: Push on VFS changes)
2024-11-09 13:27:09,352 [16485864]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [meanstacknh]
2024-11-09 13:27:14,754 [16491266]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-11-09 13:27:14,755 [16491267]  FINER - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 457
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1731176834754000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.5"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.32.4"}},"events":[{"name":"actionTriggered","params":{"engagement_time_msec":"1","session_id":"1059475b-bed2-4d5a-8519-a543ed9f06cb","action_type":"generate.ui","source":"command"}}]}
BODY END
2024-11-09 13:27:14,893 [16491405]  FINER - #dev.nx.console.nxls.NxlsWrapper - Error from nxls: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-5" org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at dev.nx.console.nxls.NxlsWrapper.start$lambda$10$lambda$9(NxlsWrapper.kt:110)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-11-09 13:27:14,893 [16491405]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-11-09 13:27:14,894 [16491406]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-11-09 13:27:14,894 [16491406]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-11-09 13:27:14,894 [16491406]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-09 13:27:14,894 [16491406]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1118236533), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@5745217d, Dispatchers.Default]
2024-11-09 13:27:14,991 [16491503]  FINER - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Security-Policy-Report-Only: script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/scaffolding/ascnsrsggc:51:0
-> Content-Type: text/plain
-> Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to=coop_reporting
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Sat, 09 Nov 2024 18:27:15 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-11-09 13:27:16,833 [16493345]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:27:16,834 [16493346]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-11-09 13:27:19,620 [16496132]   INFO - #c.i.o.c.i.s.StoreUtil - saveProjectsAndApp took 2787 ms

```

**Comment by nhhockeyplayer** [comment] 2024-11-09 18:30
here is latest log when we click the "+" NX Generate UI button on the console itself within webstorm IDE frame

tail -f ~/Library/Logs/JetBrains/WebStorm2024.1/idea.log | tee idea.output.log
```
BODY START

BODY END
2024-11-09 13:27:16,833 [16493345]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:27:16,834 [16493346]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-11-09 13:27:19,620 [16496132]   INFO - #c.i.o.c.i.s.StoreUtil - saveProjectsAndApp took 2787 ms
2024-11-09 13:27:38,559 [16515071]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:27:38,559 [16515071]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-11-09 13:28:50,118 [16586630]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:28:50,118 [16586630]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-11-09 13:29:37,956 [16634468]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-11-09 13:29:37,957 [16634469]  FINER - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 457
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1731176977956000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.5"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.32.4"}},"events":[{"name":"actionTriggered","params":{"engagement_time_msec":"1","session_id":"1059475b-bed2-4d5a-8519-a543ed9f06cb","action_type":"generate.ui","source":"command"}}]}
BODY END
2024-11-09 13:29:38,152 [16634664]  FINER - #dev.nx.console.nxls.NxlsWrapper - Error from nxls: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-3" org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at dev.nx.console.nxls.NxlsWrapper.start$lambda$10$lambda$9(NxlsWrapper.kt:110)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-11-09 13:29:38,153 [16634665]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-09 13:29:38,154 [16634666]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1118236533), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@131b816e, Dispatchers.Default]
2024-11-09 13:29:38,169 [16634681]  FINER - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Security-Policy-Report-Only: script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/scaffolding/ascnsrsggc:51:0
-> Content-Type: text/plain
-> Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to=coop_reporting
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Sat, 09 Nov 2024 18:29:38 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Report-To: {"group":"coop_reporting","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/scaffolding/ascnsrsggc:51:0"}],}
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-11-09 13:29:38,969 [16635481]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-11-09 13:29:38,969 [16635481]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files

```

**Comment by MaxKless** [comment] 2024-11-11 07:30
Hello. Did you read @Coly010 reply in your nx issue? This is an issue with an unused dependency you have installed. 
I'll close this for now a duplicate of https://github.com/nrwl/nx-console/issues/2071

**Closed** 2024-11-11 07:30 UTC
Labels: type: bug

**Comment by nhhockeyplayer** [comment] 2024-11-14 12:25
> Hello. Did you read [@Coly010](https://github.com/Coly010) reply in your nx issue? This is an issue with an unused dependency you have installed. I'll close this for now a duplicate of [#2071](https://github.com/nrwl/nx-console/issues/2071)

thanks friend...
i looked at #2701

still lost as to what course of action im suppose to take
do I remove something from my package.json?

I just migrated to latest Nx and the nx-console UI shows up now

But your stating I need to take some action?

clarification please, thanks

**Comment by MaxKless** [comment] 2024-11-14 13:27
Sorry, I linked to the wrong issue. I was talking about https://github.com/nrwl/nx/issues/28388
And the response Colum gave you. That's what's required to fix this. Thanks
