### ISSUE TITLE
IJ plugin to use settings defined node binary

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx-console#1633] opened 2023-03-25 15:26 UTC
## Description

In an enterprise environment node is not always installed globally.

IJ IDEA caters for this by allowing us to specify the node binary location.

The plugin currently is looking for the node binary in a global location and fails since it is not found.

## Motivation

Work in non default setups.

**Comment by bulldog98** [comment] 2023-03-27 06:28
Is this a duplicate of #1614 ?

**Comment by Cammisuli** [comment] 2023-03-27 12:07
Yup duplicate of #1614

**Closed by Cammisuli** 2023-03-27 12:07 UTC
Labels: type: feature
