### ISSUE TITLE
Use nx-console in a multi-module Maven project

### ISSUE THREAD

**Issue by eilensm** [nrwl/nx-console#1588] opened 2023-03-03 08:39 UTC
## Description

I have a project which is a maven reactor module consisting of a (hierarchy) of multiple maven modules like so:

my-root (project)
|- module a
|- module b
   |- backend (Spring boot java application)
   |- frontend (angular frontend project with Nx)

The plugin seems to have a problem with this structure and looks for a node_modules directory in the root folder ("my-root/node_mdules") but does not find one.

## Motivation

I think this project setup is quite a common one and nothing really special.

## Suggested Implementation

Maybe some configuration options for pointing the plugin to the path, where the node_modules directy is and where the nx.json lives? (the communiy plugin Nx console IDEA plugin does have such an option).

**Comment by MaxKless** [comment] 2023-03-03 08:51
Hey @eilensm thanks for reporting this! 
This is a duplicate of https://github.com/nrwl/nx-console/issues/1560 and has been fixed already in `1.2.0`. 

If dont want to wait for the update to appear in the jetbrains marketplace, you can download the release here: [intellij-v1.2.0 (release)](https://github.com/nrwl/nx-console/releases/tag/intellij-v1.2.0)

Download the zip, and follow these instructions [jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)

**Closed by MaxKless** 2023-03-03 08:51 UTC
Labels: type: feature
