### ISSUE TITLE
NX Console opening external terminal windows capturing focus

### ISSUE THREAD

**Issue by CodeWithBryan** [nrwl/nx-console#1442] opened 2022-12-15 00:27 UTC
## Current Behavior

Currently, with NX Console enabled, various things cause it to open an external console window. This grabs the keyboard focus away from VSCode and stops what you're doing. The most obvious time is when you open vscode, but happens when files are opened sometimes, or when new files are created.

## Expected Behavior

It shouldn't open external terminal windows that steal your focus.

## Steps to Reproduce

1. Generate a brand new NX Project
2. Enable NX Cloud
3. Install the NX Console plugin to VS Code
4. Open the project in vscode

### Failure Logs / Images / Videos

Here's a video of what's happening.

https://user-images.githubusercontent.com/3913534/207743966-064945f4-b010-4f3b-b62b-e18608ec2d52.mp4

### Environment

Brand new NX project, no packages created yet.
```
  "dependencies": {},
  "devDependencies": {
    "@nrwl/js": "15.3.3",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "15.3.3",
    "nx": "15.3.3",
    "prettier": "^2.6.2",
    "typescript": "~4.8.2"
  }
  ```

- Nx Console version: v17.27.1
- VSCode version: 1.74.0
![image](https://user-images.githubusercontent.com/3913534/207744097-a7872d09-457f-49e3-bb67-7ff055772aa9.png)

**Comment by CodeWithBryan** [comment] 2022-12-15 00:29
Might actually be a duplicate of https://github.com/nrwl/nx/issues/10822

**Comment by MaxKless** [comment] 2022-12-15 09:36
Interesting. I've never seen this before. It looks like a windows-specific behaviour. Have been able to recreate it on macos or linux by any chance?

**Comment by CodeWithBryan** [comment] 2022-12-21 07:30
Confirmed happening outside and without NX-Console. So it leads me to believe it's more an issue elsewhere in the NX Pipeline.

I'm unable to test linux/macos at the moment

**Comment by MaxKless** [comment] 2022-12-21 08:37
Ok thanks for the info. In that case Im closing it as a duplicate of [nrwl/nx#10822](https://github.com/nrwl/nx/issues/10822)

**Closed by MaxKless** 2022-12-21 08:37 UTC
Labels: type: bug
