### ISSUE TITLE
exit code 127 on any generation

### ISSUE THREAD

**Issue by bable3** [nrwl/nx-console#1505] opened 2023-02-02 11:04 UTC
## Current Behavior

When i try any generate command with the console the dry run and the run return this error 

`Executing task: npx nx generate @nrwl/angular:component test --project=ui-kit --path=libs/ui-kit/src/lib --no-interactive --dry-run`

`/bin/bash: npx: command not found
The terminal process "/bin/bash '-c', 'npx nx generate @nrwl/angular:component test --project=ui-kit --path=libs/ui-kit/src/lib --no-interactive --dry-run'" terminated with exit code: 127. 
 Terminal will be reused by tasks, press any key to close it.
 If I open an integrated terminal and execute  
 npx nx generate @nrwl/angular:component test --project=ui-kit --path=libs/ui-kit/src/lib --no-interactive`

it works

## Expected Behavior

It supposed to generate test component

- Nx Console version: v17.29.0
- VSCode version: v1.74.3

**Comment by MaxKless** [comment] 2023-02-02 11:31
This looks like a duplicate of #1424
If you could try the proposed fix there and report back that would be great!

**Closed by MaxKless** 2023-02-02 11:31 UTC
Labels: type: bug
