### ISSUE TITLE
Intellij Idea  with NX Console opens project.json with Data Editor and Viewer if form of a table 

### ISSUE THREAD

**Issue by mikhail-g** [nrwl/nx-console#2125] opened 2024-05-07 16:11 UTC
## Current Behavior

Intellij Idea  with NX Console opens `project.json` with Data Editor and Viewer if form of a table. [Data Editor and Viewer](https://www.jetbrains.com/help/idea/data-editor-and-viewer.html) is bundled and enabled in IntelliJ IDEA by default.
I tried with both  Database Tools and SQL plugin enabled and disabled (see link above)

`package.json` opens normally

## Expected Behavior

`project.json` should be shown as json file

## Steps to Reproduce

1. Open nx project with Intellij Idea Ultimate
3. Install NX Console plugin
4. open project.json

### Failure Logs / Images / Videos

<img width="459" alt="Screenshot 2024-05-07 at 17 57 44" src="https://github.com/nrwl/nx-console/assets/7706989/9a1065a5-cec4-42d4-bfe9-86a81f18b850">

### Environment
Intellij Idea (Host)
OS: macOS 13.6.6 (22G630)

Intellij Idea (server) - connected via coder to linux workspace:
   Node   : 20.5.1
   OS     : linux-x64
   npm    : 9.8.0

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/node           : 18.0.4
   @nx/react          : 18.0.4
   @nx/storybook      : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   nx-stylelint : 17.1.4

- Nx Console version:
    - 1.23.1
- Intellij Ultimate version version:
    - IntelliJ IDEA 2024.1.1
    - Build #JBC-241.15989.150, built on April 29, 2024

**Comment by MaxKless** [comment] 2024-05-08 13:42
Hey! Thanks for the report.
Can you specify what you mean by 'if form of a table'?
For me, `project.json` files open normally in IntelliJ IDEA Ultimate. 

Please provide a minimal reproduction as that is the fastest way for me to see the same issue you're seeing and to help fix it! 
Thank you :)

**Comment by Den-dp** [comment] 2024-06-03 19:18
@MaxKless don't have clear steps right now, but for me, it's a combination of Rider, Nx, and this `Database Tools` plugin 

![image](https://github.com/nrwl/nx-console/assets/1770529/c54877c2-e09f-4cd3-bb24-b5d8932c593f)

for some reason, they started to add an extra floating action button and 2 tabs underneath in every json file

![image](https://github.com/nrwl/nx-console/assets/1770529/15030d83-13b7-4fb0-bc18-3db6ebb9b855)
![image](https://github.com/nrwl/nx-console/assets/1770529/f472cb9c-92ba-407d-aa4c-ad036122a2db)

But it might be something JetBrains-related cause I don't have this problem in WebStorm with installed Nx and Database Tools.

**Comment by MaxKless** [comment] 2024-06-07 10:04
Interesting... the refresh floating action button was added by Nx Console to be able to refresh to language server.
It seems like a combination of plugins & Rider, maybe you can report it to JetBrains?
But since it looks like you can just select the `TextEditorWithPreview` in order to get the correct view, it shouldn't be a problem, right?

I'll close this for now as it's not actionable for me :)

**Closed by MaxKless** 2024-06-07 10:04 UTC
Labels: type: bug, blocked: more info needed
