### ISSUE TITLE
NX  Missing Platform Dependency (darwin-x64) when executing build, serve or test on new workspace

### ISSUE THREAD

**Issue by TomWhiteIMO** [nrwl/nx-console#1820] opened 2023-07-12 13:57 UTC
## Current Behavior

Using Nx Console to build, serve or test an Angular application created in a new 16.5.0 Nx Workspace results in the following error:

>  Executing task: npx nx run my-app:test 
>  NX   Missing Platform Dependency
>  The Nx CLI could not find or load the native binary for your supported platform (darwin-x64).

However if I copy the generated cli command into my terminal, it runs fine there.

## Expected Behavior

Nx Console should be able to run the command like the Terminal cli command can

## Steps to Reproduce

1. npm create nx-workspace
2. Which stack do you want to use? choose Angular
3. Standalone project or integrated monorepo? choose Integrated Monorepo
4. Default stylesheet format - choose SASS
5. rest of options - choose defaults
6. Open new workspace in VSCode
7. Try build, serve or test from Nx Console

### Environment

OS: macOS Ventura 13.4.1

- Nx Console version: v18.5.0
- VSCode version: 1.80.0 (Universal)

**Comment by MaxKless** [comment] 2023-07-12 14:06
closing as a duplicate of https://github.com/nrwl/nx-console/issues/1810

**Closed by MaxKless** 2023-07-12 14:06 UTC
Labels: type: bug
