### ISSUE TITLE
Failure while generating Angular library in IntelliJ due to "Schematic input does not validate against the Schema"

### ISSUE THREAD

**Issue by christophercr** [nrwl/nx-console#1602] opened 2023-03-10 15:57 UTC
## Current Behavior

When running the "generate Angular library" command from the Nx Console in IntelliJ, there is a dry-run of the schematics involved, however it fails due the name not matching a required pattern. 

I put the output in the IntelliJ console of the command triggered by the Nx Console below.

## Expected Behavior
The Angular library should be created with no issues.

In fact, when running the schematics manually in the terminal, it works fine: `npx nx g @nrwl/angular:library --name=mylib --buildable`

### Failure Logs / Images / Videos

```
C:/some/path/to/my/project/node_modules/.bin/nx.cmd g @nrwl/angular:library --name=mylib --buildable --directory=C:/som/path/to/my/project/libs --no-interactive --dry-run

>  NX  Generating @nrwl/angular:library

InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"c:-some-path-to-my-project-libs-mylib","prefix":"someprefix","entryFile":"index","skipPackageJson":false,"skipTsConfig":true}
Errors:

  Data path "/name" must match pattern "^(?:@[a-zA-Z0-9-*~][a-zA-Z0-9-*._~]*/)?[a-zA-Z0-9-~][a-zA-Z0-9-._~]*$".
    at MapSubscriber.project (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:30:27)
    at MapSubscriber._next (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (C:\some\path\to\my\project\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\some\path\to\my\project\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\some\path\to\my\project\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\some\path\to\my\project\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:143:22)
    at ThrowIfEmptySubscriber._next (C:\some\path\to\my\project\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26) {
  errors: [
    {
      instancePath: '/name',
      schemaPath: '#/properties/name/pattern',
      keyword: 'pattern',
      params: [Object],
      message: 'must match pattern "^(?:@[a-zA-Z0-9-*~][a-zA-Z0-9-*._~]*/)?[a-zA-Z0-9-~][a-zA-Z0-9-._~]*$"'
    }
  ]
}

 >  NX   Schematic input does not validate against the Schema: {"name":"c:-some-path-to-my-project-libs-mylib","prefix":"someprefix","entryFile":"index","skipPackageJson":false,"skipTsConfig":true}

   Errors:
   
     Data path "/name" must match pattern "^(?:@[a-zA-Z0-9-*~][a-zA-Z0-9-*._~]*/)?[a-zA-Z0-9-~][a-zA-Z0-9-._~]*$".
   Pass --verbose to see the stacktrace.
```

### Environment

- Nx Console version: 1.2.0
- VSCode version: n/a
- IntelliJ: WebStorm 2022.3.3

**Comment by AgentEnder** [comment] 2023-03-10 16:27
It looks like the path is the full path rather than relative to the workspace layout directory, which is likely causing the issue.

**Comment by christophercr** [comment] 2023-03-10 17:00
Yes, I'm on windows. Is it really the same issue? I thought it was a different one because in my case the issue seems to be related to the name of the lib (based on the schema validation error shown in the console).

**Comment by MaxKless** [comment] 2023-03-10 17:04
hmmm it looks like you're right and I was too quick. 
Either way @Cammisuli and his new windows laptop will have a look at it!

**Comment by Cammisuli** [comment] 2023-03-16 12:23
Duplicate of #1602

**Closed by Cammisuli** 2023-03-16 12:23 UTC
Labels: type: bug, scope: windows
