### ISSUE TITLE
[WebStorm/IntelliJ] Nx console plugin causes high CPU load

### ISSUE THREAD

**Issue by FrancescoBorzi** [nrwl/nx-console#2031] opened 2024-02-24 11:49 UTC
## Current Behavior

- When the plugin is active, it often spawns a "node" process which will consume a lot of CPU.
- It seems one "node" process will be spawned per project
- It happens both on Webstorm and Intellij
- Even after you close the IDE, the `node` process will keep running until you either force-quit it or restart the machine

## Expected Behavior

This should not happen

## Steps to Reproduce

- Use `WebStorm 2023.3.4`
- Install `Nx Console 1.18.0` and enable the plugin
- Observe the high CPU load caused by some `node` process
- Not sure if this makes a difference, probably not, but I tried on several Angular-based projects

### Failure Logs / Images / Videos

No logs available

### Environment

- macOS 13.6.3
- Nx Console version: 1.18.0
- WebStorm version: 2023.3.4
- (also tried on IntelliJ)

**Comment by MaxKless** [comment] 2024-02-26 11:38
The `node` process is the nxls which is needed to provide information about nx. It should shut down correctly though, so that's definitely a bug.

**Comment by fgloppe-cedreo** [comment] 2024-03-04 16:06
I have the same thing on Intellij Idea 2023.3.4 / nx-console 1.19 / MacOS 13.6.4 / Node 18

**Comment by stefanlivens** [comment] 2024-03-15 12:48
Same here. MacOS 14.3.1, WebStorm 2023.3.4, nx-console 1.19
Webstorm will consume 1000% cpu.

oh, i just wanted to reproduce it, and for kicks i tried the 'File' > 'Repair IDE', clicked trough the steps, and lo and behold. My machine behaves (again)!

**Comment by stefanlivens** [comment] 2024-03-15 13:18
I spoke too soon: the spike is back

 %CPU  Subsystem

419.8  <Process total CPU usage>
311.5  <unidentified: DefaultDispatcher-worker->

Basicly it is impossible to work with the plugin active

**Comment by MaxKless** [comment] 2024-03-15 14:46
some fixes for disposing and coroutine mgmt will come with the next release. would be great if you could lmk if that will improve things.

**Comment by MaxKless** [comment] 2024-03-20 12:47
Hey! Can you check out `idea.log` and paste the contents here? 
I have a hunch that this is because something is wrong with file watching in IntelliJ and more files than needed are being picked up. 
Would be great if you could provide more info.

**Comment by stefanlivens** [comment] 2024-03-29 13:41
Off course, when i started to prepare to get this log ready by cleaning out the logs, I can't reproduce it anymore.
Also installed the latest version (1.20.0) and the issue is (not) there anymore. Or at least a lot less.

**Comment by MaxKless** [comment] 2024-04-02 09:21
Hey! I think this definitely has something to do with file watching in Nx Console. Please check the `idea.log` contents and be sure to insert `#dev.nx.console:trace` under `Help` > `Diagnostic Tools` > `Debug Log Settings.`
Are you using `yarn pnp` by any chance, @FrancescoBorzi @stefanlivens

**Comment by MaxKless** [comment] 2024-04-10 10:18
Okay that's good to know, thanks.
Any chance you could provide those logs?

**Comment by polyakov84** [comment] 2024-04-23 16:24
I've got issues with node process CPU sage after closing PyCharm 2024.1. Everything works well before I close the PyCharm. After closing the node process doesn't stop and use 150% of CPU.

M1Pro Macbook

**Comment by jaysoo** [comment] 2024-04-30 17:59
@FrancescoBorzi @polyakov84 If you run `ps aux | grep node | grep -v grep | grep -e nxls -e daemon` what output do you see?

**Comment by polyakov84** [comment] 2024-05-01 05:46
@jaysoo It takes 143% of CPU and will not exit until I kill it.

<img width="912" alt="Screenshot 2024-05-01 at 08 42 55" src="https://github.com/nrwl/nx-console/assets/1419526/348f48e5-d591-44b0-8233-511f924b6647">

**Comment by jaysoo** [comment] 2024-05-01 17:35
@polyakov84 When you kill it, did `kill` work, or did you have to use `kill -9`? I've seen the nxls process hanging before, trying to reproduce it so we can fix.

**Comment by polyakov84** [comment] 2024-05-01 17:57
@jaysoo `kill` doesn't kill the process. The process still presents, and it increases CPU usage to 215%.

`kill -9` kills process, and there are no node processes after that.

**Comment by jaysoo** [comment] 2024-05-01 18:00
> @jaysoo `kill` doesn't kill the process. The process still presents, and it increases CPU usage to 215%.
> 
> `kill -9` kills process, and there are no node processes after that.

Thank you, that is consistent with what I observe as well. We'll fix this.

**Comment by jaysoo** [comment] 2024-05-01 19:51
If someone can link a gist of their IDEA log, that could help track down the problem.

<img width="537" alt="Screenshot 2024-05-01 at 3 51 06 PM" src="https://github.com/nrwl/nx-console/assets/53559/5e367500-3a1c-48c1-9dfd-ff2cf7f3b744">

**Comment by polyakov84** [comment] 2024-05-01 20:01
@jaysoo I don't have this menu item in PyCharm Pro. I also checked in other menus.

**Comment by jaysoo** [comment] 2024-05-01 20:06
@polyakov84 On MacOS, it'd be at `~/Library/Logs/JetBrains` under your IDE folder. For example, for me it is `~/Library/Logs/JetBrains/IntelliJIdea2024.1/idea.log`.

**Comment by MaxKless** [comment] 2024-05-02 10:33
Hey! I just released a new version of IntelliJ for JetBrains, you should see it already. 
Can you check whether the issue still persists? We now have an additional check to kill the nxls process if it doesn't shut down by itself after 2 seconds :)

**Comment by polyakov84** [comment] 2024-05-02 10:45
@MaxKless It's fixed and works well now in my case. Thanks.

**Comment by MaxKless** [comment] 2024-05-06 10:12
That's great to hear! I'm closing this issue as resolved. 
If you still run into this problem, please let me know and I'll have another look.

**Closed by MaxKless** 2024-05-06 10:12 UTC
Labels: type: bug
