### ISSUE TITLE
[intellij] Context menu Nx Refactorings should prefill the selected project name

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1729] opened 2023-05-12 22:21 UTC
## Description

Context menu Refactorings such as "Move Nx Project" and "Remove Nx Project" should prefill the selected project name (if possible)

![image](https://github.com/nrwl/nx-console/assets/1770529/6a6fc021-9159-48d9-adb5-a6a1b9bdfb3a)

## Motivation

Typing the project name after right-clicking on it feels lame

## Suggested Implementation

Prefill the project in this dialog

![image](https://github.com/nrwl/nx-console/assets/1770529/f32047a6-6756-4f66-bc60-22d1e5946072)

**Comment by MaxKless** [comment] 2023-05-15 08:21
hmmm this was working in the past, looks like a regression. I'll try to reproduce.

**Comment by MaxKless** [comment] 2023-07-06 10:57
Hey! 
I have a feeling this was fixed in https://github.com/nrwl/nx-console/pull/1792, can you check @Den-dp ?

**Comment by MaxKless** [comment] 2023-07-17 12:13
I just tried reproducing this on my windows machine, worked for me. 
Let me know if it's still broken for you :)

**Closed by MaxKless** 2023-07-17 12:13 UTC
Labels: type: bug, scope: windows, blocked: more info needed, intellij

**Comment by Den-dp** [comment] 2023-07-22 16:28
@MaxKless now it works for me on windows 🎉

Thanks and sorry for the delay
