### ISSUE TITLE
PNPM preventing NX Console or any interactive nx scripts from working at all

### ISSUE THREAD

**Issue by binaryartifex** [nrwl/nx-console#1288] opened 2022-05-31 02:12 UTC
## Current Behavior

Using PNPM as the workspace package manager, no scripts are run at all. Not the scripts within project.json files, the "Generate and run target" helpers, "common nx commands", nothing. manually triggering them seems to work just fine though. 

## Expected Behavior

NX related scripts actually run.

## Steps to Reproduce

1. Start a new workspace
```
pnpm dlx create-nx-workspace@latest --package-manager pnpm
```
2. Attempt to run any nx console scripts

### Failure Logs / Images / Videos

No errors or logs are generated. No dry run servers load up, everything is just ignored.

### Environment

Running vscode on a windows 11 OS with the latest Git Bash as my default console.
Using PNPM version 7.1.7

```
// package.json
{
  "name": "test-monorepo",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "devDependencies": {
    "@nrwl/cli": "14.1.9",
    "@nrwl/workspace": "14.1.9",
    "nx": "14.1.9",
    "prettier": "^2.5.1",
    "typescript": "~4.6.2"
  }
}
```
```
// vscode settings.json
{
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "workbench.iconTheme": "vscode-icons",
  "vsicons.dontShowNewVersionMessage": true,
  "explorer.compactFolders": false,
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash"
    }
  }
}
```

**Comment by Cammisuli** [comment] 2022-05-31 10:26
Thanks for the report. I'll boot up a windows vm and check it out as soon as I can.

**Comment by vire** [comment] 2022-06-08 12:03
with `PNPM` it did work with NX 13 for sure, but now I'm seeing

```
Project <project-name> has no root. This could be because of an error loading the workspace configuration.
```

And interesting during migration to nx14 the `root` property was deleted from all project.json

**Comment by vire** [comment] 2022-06-08 12:09
looks like duplicate of #1290

**Comment by binaryartifex** [comment] 2022-06-12 08:53
the extension has been updated, running the latest nx (14.2.4), ive uninstalled and reinstalled node modules and pnpm.lock file, went to uninstall and reinstall this extension and it only just dawned on me that on hovering over this extension in the installed extensions menu, it shows any exceptions that have occurred and im continuously getting the below error...

```
Command failed: pnpm --version 'pnpm' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by Cammisuli** [comment] 2022-06-13 10:20
Try one of these solutions, or something similar for windows settings. 

https://github.com/nrwl/nx-console/issues/1207#issuecomment-1025007577

**Comment by binaryartifex** [comment] 2022-06-16 20:27
@Cammisuli cheers mate im afraid those solutions didn't work either. The frustrating thing, is that if i open my vscode project directly from the bash command line, everything works perfectly fine. If i open vscode any other way, nothing works in this extension and the above exception keeps getting generated

**Comment by Cammisuli** [comment] 2022-06-16 20:30
Ive seen something like this happen to me, but with proxy settings. If I don't start vscode from the terminal that has the proxy on, then vscode can't communicate properly with certain endpoints. 

I think there's something that vscode needs to inherit that doesn't happen automatically. 

I can try searching on the vscode repo or stackoverflow to see if there's a way to make git bash work well.

**Comment by Cammisuli** [comment] 2022-06-17 13:24
I'm going to reopen this so that it doesn't get lost, and I can follow up in a couple days.

**Comment by neolectron** [comment] 2022-06-21 02:42
Solution mentionned in #1207 worked for me, which is adding this in vscode config :
```json
"terminal.integrated.profiles.linux": {
  "zsh": {
    "path": "zsh",
    "args": ["-i"]
  }
}
  ```

**Comment by binaryartifex** [comment] 2022-06-25 01:01
@neolectron must be something left field happening within the windows environment. Below is my vscode settings atm - even if i add the ```"args": ["-i"]``` argument to any of the below profiles the result is the same im afraid.

```
{
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "workbench.iconTheme": "vscode-icons",
  "vsicons.dontShowNewVersionMessage": true,
  "explorer.compactFolders": false,
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash",
    }
  },
  "terminal.integrated.shellIntegration.enabled": true
}

**Comment by kopach** [comment] 2023-01-26 14:29
Here is a solution which worked for me
1. open VSCode setting page
2. set `terminal.integrated.defaultProfile.osx` to null
3. restart VSCode
4. open terminal (in my case `sh` terminal was used instead of `zsh` I was using before)
5. make sure `pnpm` command available in this shell
	a. I had to run `npm install -g pnpm --force` to make it work
6. restart you VSCode
7. at this point `NX Console` extension should work
8. you can go to VSCode settings and revert `terminal.integrated.defaultProfile.osx`  to whatever you like

**Comment by bable3** [comment] 2023-02-02 13:47
I had the exact same issue and the solution of @kopach worked !

> Here is a solution which worked for me
> 
> 1. open VSCode setting page
> 2. set `terminal.integrated.defaultProfile.osx` to null
> 3. restart VSCode
> 4. open terminal (in my case `sh` terminal was used instead of `zsh` I was using before)
> 5. make sure `pnpm` command available in this shell
>    a. I had to run `npm install -g pnpm --force` to make it work
> 6. restart you VSCode
> 7. at this point `NX Console` extension should work
> 8. you can go to VSCode settings and revert `terminal.integrated.defaultProfile.osx`  to whatever you like

**Comment by smiket** [comment] 2023-03-05 13:46
If it helps anyone I also had a non-responsive NX Console.  In my case, I'm using **NVM** and my default version was set to 14 (no workspace support).  I reset that to 18 (`nvm alias default 18.14.2`) and restarted code, which fixed everything for me.  So perhaps a little different than the above cases, but worth mentioning.  Hope it helps.

**Comment by Cammisuli** [comment] 2023-04-21 11:56
I think the solutions provided by other comments in this thread is the most useful. 

Nx Console delegates all task creation to VSCode which handles the environment itself, so there's not much we can do on the extension side.

**Closed** 2023-04-21 11:56 UTC
Labels: type: bug, scope: windows, vscode

**Comment by utthiran** [comment] 2023-05-11 07:58
I had this issue in my Mac and @kopach's solution fixed it for me
