### ISSUE TITLE
Can't type slash in NX Console for Jetbrains

### ISSUE THREAD

**Issue by maxbeba** [nrwl/nx-console#1707] opened 2023-04-26 21:18 UTC
## Current Behavior

It's impossible to type a / character into the textboxes of NX console. When typing / it enters ?.
I am working on a Mac with german keyboard layout using webstorm in the latest version.
Screenshot below.

## Expected Behavior

I can type a slash...

## Steps to Reproduce

- Get a Mac with latest OS and german keyboard layout
- Install webstorm in latest version
- Install the nx console
- Run any generator and try to enter a slash

### Failure Logs / Images / Videos

![image](https://user-images.githubusercontent.com/129515369/234704460-10432793-76db-49fc-aaa6-7d9f78a6d32b.png)

### Environment

- Nx Console version: 1.3.2
- Webstorm version: latest

**Comment by Cammisuli** [comment] 2023-04-27 20:45
Oh this is interesting.. @MaxKless do you have a german keyboard?

**Comment by MaxKless** [comment] 2023-04-28 08:34
I should be able to find a german keyboard laying around somewhere :D What a unique issue haha

**Comment by maxtranslaya** [comment] 2023-05-01 07:30
@MaxKless Yes this is a great one. :-)
I just reported the same to the CodeStream guys. Maybe this is actually an issue with Jetbrains?

**Comment by maxtranslaya** [comment] 2023-05-01 07:33
@MaxKless I think you should be able to just change the layout on your mac. / is [shift]+7 on

**Comment by DaSchTour** [comment] 2023-05-14 10:40
I wonder why the other NX plugin do this so much better. No issues with characters. Values are prefilled from configuration. It's a pitty that the official NX plugin is still behind and actually not really useful at the moment.

**Comment by MaxKless** [comment] 2023-05-16 11:00
Hey @maxbeba! Thanks for the report again - I switched my keyboard to german on macos and I wasn't able to reproduce the issue... Since you found the same issue in the CodeStream plugin, maybe there's something wrong with your webstorm configuration?

**Comment by MaxKless** [comment] 2023-05-16 11:06
Hi @DaSchTour I appreciate the feedback - you could make it more constructive by providing some details :) 
What OS are you on? Where are you seeing issues with the prefilled configuration? Are you referring to the `path`, `directory` or `project` prefilling when opening the UI from a context menu?

**Comment by MaxKless** [comment] 2023-05-19 13:29
Closing this as it's an upstream issue. 
@maxbeba reported it to JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-319575/Cannot-type-slash-in-CodeStream-and-NX-Console-plugins?s=Connot-type-slash-in-plugins

**Closed by MaxKless** 2023-05-19 13:29 UTC
Labels: type: bug

**Comment by DaSchTour** [comment] 2023-05-20 10:10
@MaxKless yeah sorry for that, I put some of my current issues into this discussion #1742

**Comment by LouisLecouturier** [comment] 2023-07-01 14:02
I have the same on MacOS using an French keyboard Layout (AZERTY)
