### ISSUE TITLE
100% CPU Utilization post close

### ISSUE THREAD

**Issue by rmcguinness** [nrwl/nx-console#2058] opened 2024-03-16 19:09 UTC
## Current Behavior

While using VS Code 1.87.2 Universal, and using NRWL to start a server instances in development mode, all works fine in the IDE. However, if I quite the IDE, the processes do not stop, and then consume 100% of one core indefinitely until I kill all node instances.

Currently starting two server processes: 1) express API server, 2) Vite UI server

## Expected Behavior

When VS Code or any IDE is quite, that all processes threads were created as children threads of the parent container and the threads are reaped after shutdown.

## Steps to Reproduce

1.) Start the IDE
2.) Start an application instance(s)
3.) use cmd+q to shut down the IDE.

Watch the process manager. N number of "Node" processes left running in the background. Trace the lineage back to nx.

Unable to test with the latest nx-examples because of upstream dependency issues in HEAD.

### Failure Logs / Images / Videos

Attached all screen shots and matching process IDs (PIDs)

### Environment

Mac M2 CPU
Node v21.7.1
NRWL 2024-03-01 07:39:40

### Package.json
```json
{
  "name": "@rmcguinness/source",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.14.5",
    "@babel/preset-react": "^7.14.5",
    "@nx/eslint": "18.0.3",
    "@nx/eslint-plugin": "18.0.3",
    "@nx/express": "18.0.3",
    "@nx/jest": "18.0.3",
    "@nx/js": "18.0.3",
    "@nx/node": "18.0.3",
    "@nx/react": "18.0.3",
    "@nx/react-native": "^18.0.3",
    "@nx/vite": "18.0.3",
    "@nx/web": "18.0.3",
    "@nx/webpack": "18.0.3",
    "@nx/workspace": "18.0.3",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@svgr/webpack": "^8.0.1",
    "@swc-node/register": "~1.6.7",
    "@swc/cli": "~0.1.62",
    "@swc/core": "~1.3.85",
    "@swc/helpers": "~0.5.2",
    "@swc/jest": "0.2.20",
    "@testing-library/react": "14.0.0",
    "@types/jest": "^29.4.0",
    "@types/node": "18.16.9",
    "@types/react": "18.2.33",
    "@types/react-dom": "18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "@vitejs/plugin-react": "^4.2.0",
    "@vitest/coverage-v8": "^1.0.4",
    "@vitest/ui": "^1.0.4",
    "babel-jest": "^29.4.1",
    "cors": "^2.8.5",
    "eslint": "~8.48.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-environment-node": "^29.4.1",
    "jsdom": "~22.1.0",
    "nx": "18.0.3",
    "prettier": "^2.6.2",
    "react-native": "0.73.2",
    "react-refresh": "^0.10.0",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "typescript": "~5.3.2",
    "url-loader": "^4.1.1",
    "vite": "^5.0.0",
    "vite-plugin-dts": "~2.3.0",
    "vitest": "^1.0.4"
  },
  "dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.15.11",
    "@mui/material": "^5.15.11",
    "@mui/styled-engine-sc": "^6.0.0-alpha.17",
    "axios": "^1.0.0",
    "express": "^4.18.1",
    "formik": "^2.4.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-router-dom": "^6.22.0",
    "styled-components": "^6.1.8",
    "tslib": "^2.3.0",
    "uuid": "^9.0.1",
    "yup": "^1.4.0"
  }
}

```

[Screen Shots](https://github.com/nrwl/nx-console/files/14624958/Untitled.document.pdf)

**Comment by rmcguinness** [comment] 2024-03-16 21:00
I tested in WebStorm also, the difference is that WebStorm honors it's killing child processes where as VSCode does not. I also tested with the following flags and got the same behavior:

```yaml
"terminal.integrated.confirmOnExit": "always",
"terminal.integrated.confirmOnKill": "always",
```

Even though the process alerts as killed, it's still leaving zombies.

**Comment by MaxKless** [comment] 2024-03-18 09:21
I'm aware of this and working on a fix :) Sorry about that

**Comment by MaxKless** [comment] 2024-03-18 09:23
closing as duplicate of https://github.com/nrwl/nx-console/issues/1731

**Closed by MaxKless** 2024-03-18 09:23 UTC
Labels: type: bug

**Comment by luco** [comment] 2025-05-28 19:46
Is this fixed? Getting this as well on v20

**Comment by MaxKless** [comment] 2025-05-29 07:27
I think this is an issue that we inherit from nx itself.... is it still happening on the latest nx versions?

**Comment by luco** [comment] 2025-05-29 17:00
Yes, using `20.0.0` and it's spiking cpu.
