### ISSUE TITLE
schema with key or id "service" already exists

### ISSUE THREAD

**Issue by kfeinUI** [nrwl/nx-console#1141] opened 2021-09-22 15:09 UTC
The extension seems to now have trouble loading for me. Had both VS Code and project updates (Angular and some nx structural) happen, so not apparent where the fault may be. It reports the below uncaught error associated with the extension.

Had been working fine previously. Now missing all but a few of the nx items in the command menu. Launching the commands from the extension's panel does seem to work. Not a total loss, though inconvenient. I did try reinstalling the extension.

**OS:** Windows 10
**VS Code:** 1.60.1
**Extension Version:** 17.10.0
**Angular:** 12
**@nrwl Packages:** 11.0.4

`workbench.desktop.main.js:1992 [[object Object]]schema with key or id "service" already exists`

```
$onExtensionRuntimeError @ workbench.desktop.main.js:1992
workbench.desktop.main.js:1992 Error: schema with key or id "service" already exists
at Ajv._checkUnique (c:\Users\***\.vscode\extensions\nrwl.angular-console-17.10.0\main.js:9822:19)
at Ajv._addSchema (c:\Users\***\.vscode\extensions\nrwl.angular-console-17.10.0\main.js:9813:22)
at Ajv.runCompileAsync (c:\Users\***\.vscode\extensions\nrwl.angular-console-17.10.0\main.js:9526:30)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async CoreSchemaRegistry._flatten (c:\Users\***\.vscode\extensions\nrwl.angular-console-17.10.0\main.js:28468:26)
```

**Comment by Cammisuli** [comment] 2021-09-23 19:14
This is interesting.. This looks like it could be related to something within Angular itself. I'll try with the latest version of Angular. 

The only reason why I feel like this is the issue is because of the `Ajv.checkUnique` call. The Angular CLI uses that :thinking:

**Comment by kfeinUI** [comment] 2021-09-24 18:20
Found that the Generate action from the panel doesn't work, while the others do.

**Comment by kfeinUI** [comment] 2021-09-27 13:46
I tracked this down to some of our generator schemas not having unique _id_ values. They duplicated the value "service", presumably from copying.

Maybe a non-issue on your end. It had previously been working, so something must have changed to apply the uniqueness assumption.

**Comment by Cammisuli** [comment] 2022-01-21 22:19
This should be fixed now as we don't use the Angular CLI to register any schemas now. We don't validate that as strictly as the Angular CLI. Let me know if this issue is still happening to you and we can look into this more.

**Closed by Cammisuli** 2022-01-21 22:19 UTC
Labels: type: bug, scope: windows
