### ISSUE TITLE
nx debug fails to start with a weird console message: ^[[7;1R

### ISSUE THREAD

**Issue by kalvintamas** [nrwl/nx-console#2179] opened 2024-06-21 09:43 UTC
## Current Behavior

When running nx serve run configuration, the above message is printed to the console, and the app doesn't start.

## Expected Behavior

Expected to run.

## Steps to Reproduce

I don't really know how to reproduce this. This bug just appears sometimes (ca. 20% of start attempts), and sometimes it doesn't.

I downloaded nx-examples and after some struggle, I could start it, I tried it a few times, but since I don't know what triggers this, I couldn't really do much.
This project is a company project I would not share public, but I collected IntelliJ logs, I hope they help.

### Failure Logs / Images / Videos

    <project_path>\node_modules\.bin\nx.cmd run bdpst-fs-frontend:serve
    Debugger listening on ws://127.0.0.1:57319/8319f305-8d38-436c-acc8-c43edea67b30
    For help, see: https://nodejs.org/en/docs/inspector
    Debugger attached.

    > nx run bdpst-fs-frontend:serve:development

    ^[[7;1R

I also collected IntelliJ logs that I attached.
[idea.log](https://github.com/user-attachments/files/15925800/idea.log)

### Environment

```
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 19.1.0
nx                 : 18.1.3
@nx/js             : 18.3.4
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/angular        : 18.3.4
@nx/cypress        : 18.1.3
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.1.3
@nrwl/tao          : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.3.4
typescript         : 5.3.2
---------------------------------------
Community plugins:
@ngrx/component         : 17.2.0
@ngrx/component-store   : 17.2.0
@ngrx/effects           : 17.2.0
@ngrx/eslint-plugin     : 17.2.0
@ngrx/operators         : 17.2.0
@ngrx/router-store      : 17.2.0
@ngrx/store             : 17.2.0
@ngrx/store-devtools    : 17.2.0
ngrx-immer              : 2.2.0
ngx-extended-pdf-viewer : 19.7.1
ngx-spinner             : 16.0.2
ngx-toastr              : 17.0.2
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@18.3.4
  - @nrwl/js@18.3.4
  - @nx/angular@18.3.4
  - @nrwl/angular@18.3.4
  - @nx/devkit@18.3.4
  - @nrwl/devkit@18.3.4
  - @nx/webpack@18.3.4
  - @nrwl/webpack@18.3.4

To fix this, run `nx migrate nx@18.3.4`
```

- Nx Console version: 1.26.0
- IntelliJ version: 2024.1.3 (Ultimate)

**Comment by MaxKless** [comment] 2024-06-21 10:12
Hey thanks for the report! 
This is very likely a duplicate of https://github.com/nrwl/nx/issues/22358

We're still working on a proper fix for this but for now you can set 
```NX_NATIVE_COMMAND_RUNNER=false``` in your root `.env` file as a workaround.

I'll close this as a duplicate but let me know if you run into any other issues :)

**Closed by MaxKless** 2024-06-21 10:12 UTC
Labels: type: bug
