### ISSUE TITLE
VSCode extension stays in memory after VSCode is closed

### ISSUE THREAD

**Issue by akv-mshin** [nrwl/nx-console#1801] opened 2023-07-04 03:28 UTC
## Current Behavior

I'm using NX Console VSCode extension, and whenever I close my VSCode, I see an orphan process in Activity Monitor. Quick check on empty profile (with only NX Console installed) shows, that the issue has to be in NX Console extension.

## Expected Behavior

NX console should completely quit and free resources when VS Code exits. Not sure if that was regression.

## Steps to Reproduce

1. Create a project with `npx create-nx-workspace@latest myorg --preset=ts` 
2. Open the project in VS Code.
3. Close VS Code.
4. See 1 Code Helper process in Activity Monitor.

Repro video:

https://github.com/nrwl/nx-console/assets/109829272/b790b72b-e1c1-455b-95ae-1b7d2c2c30aa

VS Code profile that can be used for repro:

[nx-repro.code-profile.zip](https://github.com/nrwl/nx-console/files/11944005/nx-repro.code-profile.zip)

### Environment

**NX Console extension version**: v18.3.0

**VS Code about info:**

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**NX report:**
```sh
▶ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : darwin-arm64
   npm    : 8.11.0

   nx             : 16.4.2
   @nx/js         : 16.4.2
   @nx/workspace  : 16.4.2
   @nx/devkit     : 16.4.2
   @nrwl/tao      : 16.4.2
   typescript     : 5.1.6
```

**Comment by MaxKless** [comment] 2023-07-04 07:39
Thanks for reporting this, @akv-mshin! I'll close it as a duplicate of https://github.com/nrwl/nx-console/issues/1731 but I'll have a deeper look, this really sucks.

**Closed by MaxKless** 2023-07-04 07:39 UTC
Labels: type: bug
