### ISSUE TITLE
projectName select empty in VS Code

### ISSUE THREAD

**Issue by Tom4U** [nrwl/nx-console#1958] opened 2023-12-13 08:48 UTC
## Current Behavior

Running the UI generator, select field (dropdown) is empty and does not show projects.

## Expected Behavior

Select should show existing/available projects in workspace.

## Steps to Reproduce

* Install VS Code and NX extension
* Create workspace with Angular application
* Run a generator that is using argument projectName (i.e. _move)_

### Failure Logs / Images / Videos

No failures visible or in daemon.log

### Environment

```
   Node   : 20.9.0
   OS     : win32-x64
   npm    : 10.2.5

   nx (global)        : 17.2.3
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/angular        : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/nest           : 17.2.3
   @nx/node           : 17.2.3
   @nx/playwright     : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   @nx/webpack        : 17.2.3
   typescript         : 5.2.2
```

- Nx Console version: 18.10.1
- VSCode version: 1.85.0 (latest)

**Comment by MaxKless** [comment] 2023-12-13 10:57
Hey! 
I can't repro this on windows or macos... do you have any more information?
Does it happen for every generator with a `project` option? 
Maybe you could share a screen recording of it happening? That would make it a lot easier for me to find the issue :)

**Comment by Tom4U** [comment] 2023-12-13 11:10
Yes, it seems to happen for all generators. Just picked two of them (pls. see screenshots), but is happening with any kind of generator where I'm supposed to select a project.
<img width="505" alt="Screenshots_Project_Selection" src="https://github.com/nrwl/nx-console/assets/31515233/46e432f3-38ad-479f-b309-576c0a0c2752">

**Comment by MaxKless** [comment] 2023-12-13 12:40
okay but all other places where you can look at your projects show the correct projects?
- the project view sidebar?
- `nx show projects`?

**Comment by MaxKless** [comment] 2023-12-13 14:05
Could you provide a reproduction repo? That would help me a lot because I don't see this error myself.

**Comment by Tom4U** [comment] 2023-12-14 10:57
Pointing on the sidebar was the trick. I've noticed, that no projects have been listed there. After refreshing the view, they came up and now the select is also filled with the projects. So maybe it would be helpful if after changes of the workspace files a refresh could be triggered automatically?

**Comment by MaxKless** [comment] 2023-12-14 13:23
yes that's happening already and will soon be improved / made more consistent. 
I'll close this issue for now :)

**Closed by MaxKless** 2023-12-14 13:23 UTC
Labels: type: bug, blocked: more info needed
