### ISSUE TITLE
Nx console hangs between commands invoked via console

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx-console#1719] opened 2023-05-04 09:54 UTC
## Current Behavior

If I run any command via the Nx console after the command is finished, Nx Console hangs for 10-15 seconds even for simple echo commands.

## Expected Behavior

It's been an issue for awhile, several major versions, can't remember before that.

## Steps to Reproduce

 N/A

### Failure Logs / Images / Videos

![image](https://user-images.githubusercontent.com/48436581/236171405-c4f8739d-7306-4192-9ad3-fc5e876f8362.png)

### Environment

- Nx Console version: 18.1.1
- VSCode version: 
```
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

The console also hangs for similar time if I run the generated commands in the terminal separately

**Comment by MaxKless** [comment] 2023-05-04 13:55
from what I understand this behavior is the same when you run the commands via the terminal? Not just in Nx Console?

**Comment by AdditionAddict** [comment] 2023-05-04 18:22
Yes, terminal within vscode. I saw similar thing happen during a Jason Warner stream (uses windows too).

**Comment by MaxKless** [comment] 2023-05-05 08:14
So it sounds like the issue isn't actually related to nx console, right? 

Are you sure it's been around for many major versions? I heard something similar but only in the latest versions.

**Comment by AdditionAddict** [comment] 2023-05-05 11:10
> So it sounds like the issue isn't actually related to nx console, right?
> 
> Are you sure it's been around for many major versions? I heard something similar but only in the latest versions.

It's definitely nx console that is blocked e.g. have to wait before button press trigger next command and nx console has the timer icon. But not sure if nx console is the cause.

My memory is blurry, 50:50 whether is was present in v14 but present v15-16.

**Comment by MaxKless** [comment] 2023-10-12 11:27
Hi @AdditionAddict. Is this still happening on the latest nx & nx console?

**Comment by bramjoosten** [comment] 2023-12-20 10:40
bump, I have this issue. 10 sec of nothingness before things happen.

**Comment by MaxKless** [comment] 2023-12-20 12:15
can you share a minimal reproduction so I can test it out?

**Comment by AdditionAddict** [comment] 2023-12-20 15:00
Apologies - not sure why I miss notifications on this - I've moved off windows since posting with latest Nx - no issues

**Comment by ManoloTonto1** [comment] 2024-01-08 17:45
![image](https://github.com/nrwl/nx-console/assets/74105210/05234e51-0c14-4e98-a047-884cfcfb2299)

Still getting same issue on ubuntu, using:
- bun v1.0.21
- nx  v17.2.8

**Comment by MaxKless** [comment] 2024-04-02 11:33
I'm closing this for now since there's hasn't been any activity for a while. If you still see this error, please let me know and we can investigate.

**Closed by MaxKless** 2024-04-02 11:33 UTC
Labels: type: bug, os: windows, vscode
