### ISSUE TITLE
Couldn't find any projects

### ISSUE THREAD

**Issue by BoilerTom90** [nrwl/nx-console#2108] opened 2024-04-27 15:43 UTC
I created a new nx workspace for an angular project.  

![image](https://github.com/nrwl/nx-console/assets/17208255/b1e61528-2ecb-4bdd-8ace-3091b91d87dd)

I've opened vscode in the project root, and when I open the nx console, it says "we can't find any projects in this workspace."  

![image](https://github.com/nrwl/nx-console/assets/17208255/0bdeeb8a-46c4-4cf3-8a22-c9f873007469)

Refreshing does nothing.   I can run the "nx serve <project>" command from the CLI and it works so I know I'm in the project workspace.

## Current Behavior
Nx Console says it can't find any projects. 

## Expected Behavior
I was expecting the nx console to find my angular project. I've tried uninstalling and reinstalling, and also restarting vscode, but it can't find my project. 

### Environment

```
$ nx report

 NX   Report complete - copy this into the issue template

Node   : 18.18.2
OS     : win32-x64
npm    : 9.8.1

nx (global)        : 18.3.4
nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/angular        : 18.3.4
@nx/cypress        : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.4.5

Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```
---------------------------------------

- Nx Console version: 18.12.0
- VSCode version:   1.82.2

**Comment by Hypenate** [comment] 2024-04-29 07:50
Having the same issue (in VS code and Webstorm).
When pressing 'Refresh Workspace' in VS code gives me this output:

> Telemetry: production
> Graph - init
> Error: Request nx/reset failed with message: Command failed: pnpm exec nx reset
> nx reset
> 
> Clears all the cached Nx artifacts and metadata about the workspace and shuts down the Nx Daemon.
> 
> Options:
>   --help     Show help  [boolean]
>   --version  Show version number  [boolean]
> 
> Error: EPERM: operation not permitted, unlink 'c:\git\bla\.nx\cache\18.3.3-nx.win32-x64-msvc.node'
>     at unlinkSync (node:fs:1878:11)
>     at _unlinkSync (node:internal/fs/rimraf:214:14)
>     at fixWinEPERMSync (node:internal/fs/rimraf:306:5)
>     at rimrafSync (node:internal/fs/rimraf:200:14)
>     at node:internal/fs/rimraf:253:9
>     at Array.forEach (<anonymous>)
>     at _rmdirSync (node:internal/fs/rimraf:250:7)
>     at fixWinEPERMSync (node:internal/fs/rimraf:304:5)
>     at rimrafSync (node:internal/fs/rimraf:200:14)
>     at rmSync (node:fs:1268:10) {
>   errno: -4048,
>   code: 'EPERM',
>   syscall: 'unlink',
>   path: 'c:\\git\\bla\\.nx\\cache\\18.3.3-nx.win32-x64-msvc.node'
> }

**Comment by MaxKless** [comment] 2024-04-29 07:55
Hey @BoilerTom90 could you share some logs from the `Output -> Nx Language Server` Tab as well? 
@Hypenate I'm working on an update that will fix the error message you're seeing. It really shouldn't be happening, though... Do you have another nx process running in the same repo, by any chance?

**Comment by Hypenate** [comment] 2024-04-29 08:12
@MaxKless No, I closed all nodejs instances via the Task Manager and the issue is still present.

**Comment by MaxKless** [comment] 2024-04-29 14:46
it's in the outputs tab in vscode. It could also be called `Nx Console Client` depending on your version.
![image](https://github.com/nrwl/nx-console/assets/34165455/3ae6ab9a-b53d-44c0-bbab-dea7209888bb)

**Comment by BoilerTom90** [comment] 2024-04-29 16:55
ah, thanks for that. I haven't much of a need to look in that output console, until now. When I look at the choices in the `OUTPUT` pulldown menu, I see
- `Nx Console` 
- `Nx Console Client` 

I do not see `Nx Language Server`.

There isn't much in the Nx Console output, but here's the output from the Nx  Console Client when I click the "refresh projects" button


[Nxls] - 2024-04-29T16:50:10.997Z - Retrieving workspace configuration

[Nxls] - 2024-04-29T16:50:10.998Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-04-29T16:50:10.998Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/utils/output.js

[Nxls] - 2024-04-29T16:50:10.998Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-04-29T16:50:10.999Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-04-29T16:50:11.005Z - createProjectGraphAsync

[Nxls] - 2024-04-29T16:50:11.014Z - createProjectGraphAsync successful

process.exit called with code 1
[Nxls] - 2024-04-29T16:50:11.016Z - Unable to get nx workspace configuration: Error: Daemon process terminated and closed the connection

Messages from the log:
[NX Daemon Server] - 2024-04-29T16:47:05.841Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 2. Response time: 1.
[NX Daemon Server] - 2024-04-29T16:47:05.845Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-04-29T16:47:05.846Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-04-29T16:47:05.846Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-04-29T16:47:05.846Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-04-29T16:47:05.849Z - [REQUEST]: Responding to the client. handleRequestFileData
[NX Daemon Server] - 2024-04-29T16:47:05.849Z - Done responding to the client handleRequestFileData
[NX Daemon Server] - 2024-04-29T16:47:05.849Z - Handled REQUEST_FILE_DATA. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-04-29T16:50:11.006Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-04-29T16:50:11.006Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-04-29T16:50:11.006Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-04-29T16:50:11.008Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-04-29T16:50:11.010Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-04-29T16:50:11.011Z - Time taken for 'total for creating and serializing project graph' 1.818900004029274ms
[NX Daemon Server] - 2024-04-29T16:50:11.011Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-04-29T16:50:11.011Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 2. Response time: 1.
[NX Daemon Server] - 2024-04-29T16:50:11.015Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-04-29T16:50:11.016Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-04-29T16:50:11.016Z - Closed a connection. Number of open connections: 2



More information: d:\projects\nx-xcreg\xcreg3\.nx\cache\d\daemon.log

--- it's worth nothing I have a couple other Nx projects that do not have this problem.

**Comment by MaxKless** [comment] 2024-05-06 09:14
Hey @BoilerTom90!
First of all, it looks like you're on an outdated version of Nx Console, so I'd recommend updating to ensure you have the latest bugfixes. If you're seeing these logs on nx `18.3.4`, you're really quite behind. 

Either way, I've added a PR https://github.com/nrwl/nx-console/pull/2120 which should hopefully catch this error and similar ones.

**Comment by MaxKless** [comment] 2024-05-06 12:32
I'm going to close this for now, if the issue still persists on a newer version of Nx Console please let me know. 
(I'm going to release a version with the fix from #2120 today as well)

Thank you!

**Closed by MaxKless** 2024-05-06 12:32 UTC
Labels: type: bug

**Comment by BoilerTom90** [comment] 2024-05-06 13:30
> Hey @BoilerTom90! First of all, it looks like you're on an outdated version of Nx Console, so I'd recommend updating to ensure you have the latest bugfixes. If you're seeing these logs on nx `18.3.4`, you're really quite behind.
> 
> Either way, I've added a PR #2120 which should hopefully catch this error and similar ones.

Max, I don't understand the comment. 18.3.4 is the latest version of Nx. How can I be behind?   I didn't actually see any of these issues until I went to the latest of Nx and Nx Console.

**Comment by MaxKless** [comment] 2024-05-06 13:38
Can you check your Nx Console version and paste it here?

**Comment by Hypenate** [comment] 2024-05-06 13:44
We fixed it by adding `@swc/helpers` to the package.json

**Comment by MaxKless** [comment] 2024-07-29 12:28
Is it possible you haven't updated your VSCode in a while?
