### ISSUE TITLE
Angular: support for "Standalone components"

### ISSUE THREAD

**Issue by boeschenstein** [nrwl/nx-console#1460] opened 2022-12-30 12:25 UTC
Support new Angular v15 feature "Standalone components" (get rid of modules)

**Comment by MaxKless** [comment] 2023-01-03 09:40
Hi @boeschenstein is there any specific feature you're missing in Nx Console?

Because Nx in general supports standalone components very well: https://blog.nrwl.io/generating-standalone-component-based-angular-applications-and-libraries-with-nx-35462037f6b1

**Comment by boeschenstein** [comment] 2023-01-09 07:01
It is not possible to generate NgRx support (using 'nx generate @nrwl/angular:ngrx'), because module is mandatory.

**Comment by MaxKless** [comment] 2023-01-09 14:40
Could you post the specific error message you're getting as well as information about your environment and versions? 
Please use `nx report` and paste the output here too.

**Comment by boeschenstein** [comment] 2023-01-11 06:40
Using Angular Standalone Components, there is no module available. But module is a required field:

![image](https://user-images.githubusercontent.com/38001274/211735673-dfaea2a1-d25d-425f-ac18-f57fec02bbfd.png)

Node : 19.3.0
   OS   : win32 x64
   npm  : 9.2.0

   nx : 15.3.2
   @nrwl/angular : 15.4.5
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.3.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.3.2
   typescript : 4.8.4

nx console [17.27.1](https://github.com/nrwl/nx-console/compare/v17.27.0...v17.27.1) (2022-12-12)

**Comment by MaxKless** [comment] 2023-01-11 15:05
Thanks for the info, I understand now. 
This looks like a missing feature of Nx, since we only display what the underlying Nx version gives us. 
Closing this as a duplicate of  [#13507](https://github.com/nrwl/nx/issues/13507)

**Closed by MaxKless** 2023-01-11 15:05 UTC
Labels: type: feature
