### ISSUE TITLE
25seconds delay before action actually starts

### ISSUE THREAD

**Issue by GrumpyMeow** [nrwl/nx-console#1258] opened 2022-03-14 09:40 UTC
## Current Behavior

When we click on an action in  the NX-Console a delay of constant/exact 25seconds is present since approximately 1 or 2 weeks before the action visually gets started. 
It's for actions like "Common NX commands > Migrate", "Common NX commands > Lint" and all "Projects > *" commands. 
It might be a coincidence, but it seems that the delay is for all actions which open a Terminal. After clicking on the action in the NX-console, The issue is present on multiple development systems (based on same image).

I also have an empty NX-workspace project, which doesn't has this delay. So apparently it must be specific for our NX-workspace.

I reduced our NX-workspace down to 2 projects, and the delay remained.

When i activated the "Developer tools" and the "performance profiler" in VSCode, the delay is slightly longer +/- 30seconds.

## Expected Behavior

I expect that clicking on a NX-console we expect that the action starts and not have this delay.
The issue appeared a few weeks ago. We suspect it's after a VSCode update. Although not the last one.

### Environment

I checked a few of the latest nrwl-nx versions and they all had the same delay: v17.14.1, v17.13.7, v17.12.4, v17.11.2

VSCode information is running on Windows 10 21H2, using "WSL2: Ubuntu"
```
Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

```
PS C:\Users\me> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

```
  Node : 14.17.0
  OS   : linux x64
  npm  : 6.14.13
  
  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : 12.10.0
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : 12.10.0
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```
```
 "dependencies": {
    "@agm/core": "3.0.0-beta.0",
    "@angular-builders/custom-webpack": "12.1.3",
    "@angular/animations": "12.2.14",
    "@angular/cdk": "12.2.13",
    "@angular/common": "12.2.14",
    "@angular/compiler": "12.2.14",
    "@angular/core": "12.2.14",
    "@angular/flex-layout": "12.0.0-beta.35",
    "@angular/forms": "12.2.14",
    "@angular/localize": "12.2.14",
    "@angular/material": "12.2.13",
    "@angular/material-moment-adapter": "12.2.13",
    "@angular/platform-browser": "12.2.14",
    "@angular/platform-browser-dynamic": "12.2.14",
    "@angular/router": "12.2.14",
    "@angular/upgrade": "12.2.14",
    "@babel/preset-env": "7.16.4",
    "@fortawesome/angular-fontawesome": "0.9.0",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
    "@fortawesome/free-solid-svg-icons": "5.15.4",
    "@ngrx/component-store": "12.4.0",
    "@ngrx/effects": "12.5.1",
    "@ngrx/entity": "12.5.1",
    "@ngrx/router-store": "12.5.1",
    "@ngrx/store": "12.5.1",
    "@ngx-translate/core": "12.1.2",
    "@ngx-translate/http-loader": "5.0.0",
    "@nrwl/angular": "12.10.0",
    "@dummy/dummy": "17.11.396-test",
    "angular": "1.8.2",
    "angular-gauge": "3.1.3",
    "angular-in-memory-web-api": "0.13.0",
    "bootstrap": "4.6.1",
    "cypress-xpath": "1.6.2",
    "d3": "6.7.0",
    "date-fns": "2.28.0",
    "express": "4.17.1",
    "faker": "4.1.0",
    "file-saver": "2.0.5",
    "leven": "4.0.0",
    "libphonenumber-js": "1.9.43",
    "moment": "2.29.1",
    "ngrx-forms": "6.3.6",
    "ngrx-store-localstorage": "12.0.1",
    "ngx-cookie": "4.0.2",
    "ngx-logger": "4.3.3",
    "ngx-page-scroll": "7.0.6",
    "ngx-page-scroll-core": "7.0.6",
    "ngx-take-until-destroy": "5.4.0",
    "rxjs": "6.6.7",
    "serve-static": "1.14.1",
    "tslib": "2.3.1",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.2.16",
    "@angular-eslint/eslint-plugin": "12.7.0",
    "@angular-eslint/eslint-plugin-template": "12.7.0",
    "@angular-eslint/template-parser": "12.7.0",
    "@angular/cli": "12.2.13",
    "@angular/compiler-cli": "12.2.14",
    "@angular/language-service": "12.2.14",
    "@angularclass/hmr": "3.0.0",
    "@babel/core": "7.16.0",
    "@babel/preset-typescript": "7.16.0",
    "@compodoc/compodoc": "1.1.18",
    "@ng-apimock/core": "3.4.0",
    "@ng-apimock/cypress-plugin": "2.2.0",
    "@ng-apimock/dev-interface": "3.1.0",
    "@ngneat/until-destroy": "8.1.4",
    "@ngrx/schematics": "12.5.1",
    "@ngrx/store-devtools": "12.5.1",
    "@nrwl/cli": "12.10.0",
    "@nrwl/cypress": "12.10.0",
    "@nrwl/eslint-plugin-nx": "12.10.0",
    "@nrwl/express": "12.10.0",
    "@nrwl/jest": "12.10.0",
    "@nrwl/linter": "12.10.0",
    "@nrwl/node": "12.10.0",
    "@nrwl/storybook": "12.10.0",
    "@nrwl/tao": "12.10.0",
    "@nrwl/web": "12.10.0",
    "@nrwl/workspace": "12.10.0",
    "@pmmmwh/react-refresh-webpack-plugin": "0.5.0-rc.2",
    "@storybook/addon-a11y": "6.3.13",
    "@storybook/addon-console": "1.2.3",
    "@storybook/addon-essentials": "6.3.13",
    "@storybook/addons": "6.3.13",
    "@storybook/angular": "6.3.13",
    "@storybook/builder-webpack5": "6.3.13",
    "@storybook/cli": "6.3.13",
    "@storybook/eslint-config-storybook": "3.1.2",
    "@storybook/manager-webpack5": "6.3.13",
    "@storybook/theming": "6.3.13",
    "@svgr/webpack": "5.5.0",
    "@types/d3": "6.7.5",
    "@types/express": "4.17.13",
    "@types/googlemaps": "3.43.3",
    "@types/jest": "27.0.3",
    "@types/node": "14.17.34",
    "@types/webpack-env": "1.16.3",
    "@typescript-eslint/eslint-plugin": "4.33.0",
    "@typescript-eslint/parser": "4.33.0",
    "angular-dynamic-locale": "0.1.37",
    "angular-translate-storage-local": "2.19.0",
    "audit-ci": "5.1.2",
    "autoprefixer": "8.6.5",
    "babel-loader": "8.2.3",
    "babel-plugin-angularjs-annotate": "0.10.0",
    "connect": "3.7.0",
    "copy-webpack-plugin": "9.0.1",
    "cors": "2.8.5",
    "cypress": "8.7.0",
    "cypress-file-upload": "5.0.8",
    "cypress-image-snapshot": "4.0.1",
    "cypress-plugin-tab": "1.0.5",
    "dotenv": "10.0.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.4.0",
    "eslint-formatter-json-relative": "0.1.0",
    "eslint-formatter-vso": "0.1.0",
    "eslint-plugin-cypress": "2.12.1",
    "eslint-plugin-html": "6.2.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jasmine": "4.1.3",
    "eslint-plugin-jsdoc": "37.9.5",
    "eslint-plugin-json": "3.1.0",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-sonarjs": "0.12.0",
    "eslint-plugin-yaml": "0.5.0",
    "hammerjs": "2.0.8",
    "https-browserify": "1.0.0",
    "husky": "7.0.4",
    "jest": "27.4.3",
    "jest-createspyobj": "2.0.0",
    "jest-junit": "12.3.0",
    "jest-preset-angular": "10.1.0",
    "jest-transform-stub": "2.0.0",
    "lint-staged": "12.3.4",
    "mini-css-extract-plugin": "2.1.0",
    "ng-mocks": "12.5.0",
    "ngx-translate-testing": "5.2.0",
    "patch-package": "6.4.7",
    "prettier": "2.5.1",
    "react-refresh": "0.10.0",
    "source-map-loader": "3.0.0",
    "start-server-and-test": "1.14.0",
    "stream-http": "3.2.0",
    "stylelint": "13.13.1",
    "stylelint-config-prettier": "8.0.2",
    "stylelint-config-recommended-scss": "4.3.0",
    "stylelint-config-standard": "22.0.0",
    "stylelint-prettier": "1.2.0",
    "stylelint-scss": "3.21.0",
    "terser-webpack-plugin": "5.1.1",
    "ts-jest": "27.0.7",
    "ts-node": "9.1.1",
    "typescript": "4.3.5",
    "url-loader": "3.0.0",
    "webpack": "5.47.0",
    "webpack-dev-server": "4.7.4",
    "webpack-merge": "5.8.0",
    "webpack-node-externals": "3.0.0",
    "webpack-sources": "3.0.2"
  },
``
[CPU-20220314T101217.596Z.cpuprofile.txt](https://github.com/nrwl/nx-console/files/8243853/CPU-20220314T101217.596Z.cpuprofile.txt)
`

**Comment by ZackDeRose** [comment] 2022-03-14 15:16
Hi @GrumpyMeow - appreciate you testing this on past builds (v17.14.1, v17.13.7, v17.12.4, v17.11.2).

I just tried to reproduce this issue and was unable to on my machine - I'll be trying it in a similar windows machine when I have an opportunity.

In the meantime to confirm:

+ when does the delay occur for you? specifically: before or after the Nx Console terminal opens?
+ you mentioned this does not occur for you in an empty nx workspace - if you add libraries to that workspace does the delay still not occur?
+ Does your project happen to have any circular dependencies?

**Comment by Schmale97** [comment] 2022-03-14 15:24
I am also seeing this issue, there is a large delay after clicking an action before the nx console terminal opens

**Comment by hellokingdom** [comment] 2022-03-14 15:29
@ZackDeRose I am seeing the exact same issue on MacOS Big Sur with M1 Chip. This started in the last week or so and what was previously an instant execution is causing a long delay of up to 15 seconds. There is no visual feedback you've clicked the command until eventually the terminal opens.

The delay occurs before the terminal is opened. 

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0

**Comment by ZackDeRose** [comment] 2022-03-14 15:43
Thanks to @Schmale97 and @hellokingdom for confirming this is an issue and confirming that the delay occurs before the terminal opens.

Can you confirm that there are no circular dependencies in your workspaces?

**Comment by ZackDeRose** [comment] 2022-03-14 15:53
If anyone happens to have a public repo where this issue exists too - that information would be particularly helpful

**Comment by hellokingdom** [comment] 2022-03-14 16:12
For clarity both @Schmale97 and myself are working on the same project. Unfortunately we can't make our specific repo public but will look to create one that can be shared.

We do not see any circular dependencies in our repo and more generally we feel like VS Code is slower than usual, it may be that Nx is highlighting a more general performance issue.

**Comment by GrumpyMeow** [comment] 2022-03-15 13:04
Aha... "Circular dependencies"... That is indeed the case. It's an issue we still need to fix in our codebase

**Comment by Schmale97** [comment] 2022-03-15 15:32
@ZackDeRose I am not seeing any circular dependencies in our codebase

**Comment by ZackDeRose** [comment] 2022-03-16 04:18
Thanks for the feedback - will look more into this issue.

I'll try circular deps to see if I can reproduce with that (thought I doubt it given @Schmale97 confirmed this is none in their codebase). Other likely culprit would be Nx version pairing.

I'll come back before the end of the week with any findings - if anyone can isolate the incident to a public repo in the meantime please let me know!

**Comment by ringodotnl** [comment] 2022-03-16 14:44
The 'fix' for us (me and @GrumpyMeow ) was to downgrade VS code from version 1.65 to version 1.64. Hopefully that's a hint, good luck!

Cheers,
Ringo.

**Comment by vytautas-petrikas** [comment] 2022-03-25 19:22
Same issue here

**Comment by ZackDeRose** [comment] 2022-03-28 15:54
We've still been unable to reproduce this - see @ringodotnl's message above if this is blocking you.

If anyone is able to give a reproduction repo or investigate by disabling all other add-ons ("Disable all extentions for this workspace" in the vs code command prompt) to see if that resolves the issues you're seeing please let us know!

**Comment by rbathora** [comment] 2022-03-30 07:54
@ZackDeRose tried to disable all ext. but no luck. Also tried the just new released vscode version but no luck either. Reverting to vs ode v1.64 is for now the only working solution.

**Comment by GrumpyMeow** [comment] 2022-03-31 08:37
This morning my VSCode upgraded to v1.66.0. Initially i had some issues with my WSLg, which were resolved with a `wsl --shutdown`. After this issue, i noticed that the NX-console-delay is no longer present! (Y)

**Comment by ringodotnl** [comment] 2022-03-31 08:40
@all 
After upgrading VS Code 1.66.0 and latest version of NX console (17.14.1) all issues were gone. Good luck all.

**Comment by ZackDeRose** [comment] 2022-04-08 18:25
Hey all, sounds like VsCode 1.66 is the fix! If anyone still seeing this after upgrading VsCode please let us know.

For now we'll close this ticket out :)

**Closed by ZackDeRose** 2022-04-08 18:25 UTC
Labels: type: bug
