### ISSUE TITLE
NX Console crashes when tried to be used in IntelliJ Webstorm

### ISSUE THREAD

**Issue by tomashodek** [nrwl/nx-console#1768] opened 2023-06-14 12:52 UTC
## Current Behavior

I'm using NX v15.8.5 currently on the project. When I try to run NX Generate(UI) or open the NX Console tab with task etc. it crashes and throws this error message:

```
org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
``` 

The NX generate then just does not open at all, I'll select a library or anything else and nothing happens. 

Note: In another project, it works fine, but I can't really check what's missing as there is a different configuration. I assume that some of the mandatory fields might not be filled in some config files, but I could not find which ones. 

Other colleagues have no issues with extension in VSCode (unfortunately I'm the only one with WebStrom atm).

## Expected Behavior

NX Generate UI opens and NX Console is working. 

## Steps to Reproduce

I don't have any specific configuration, everything is almost default. Here is our `nx.json` but it's really default we're just starting the project. 

```
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "scopeName", #changed for this example
  "affected": {
    "defaultBase": "main"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": ["default"],
    "sharedGlobals": []
  },
  "defaultProject": ""
}
```

### Environment

NX report: 
```
Node : 18.16.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/esbuild           : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/nx-plugin         : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx/esbuild : 16.1.1
   @nx/js      : 16.3.2
```

- Nx Console version: 1.6.1
- Webstorm version: 2023.1.2

**Comment by MaxKless** [comment] 2023-06-14 14:25
Hmm I just tested it and that combination of Nx Console + Nx versions works for me. 

Could you paste your `idea.log` after reproducing the issue? Maybe there's some more information to be found in there.

**Comment by tomashodek** [comment] 2023-06-14 14:41
Sure, here is the log around that error. Not really sure if it's helpful. My assumption is, that we removed some config line that is required for the plugin, but I can't figure out which one tbh and I'm trying to understand the config bit more then just reverting weeks of changes and randomly checking each changed line. 

[idealog.txt](https://github.com/nrwl/nx-console/files/11746941/idealog.txt)

**Comment by MaxKless** [comment] 2023-06-14 14:51
Hmm yeah, I'd love to see what request exactly causes the problem. Can you turn on the LSP logs like this: 

Go to Help > Diagnostic Tools > Debug Log Settings... and then insert #dev.nx.console:trace

and then post idealog.txt again?

**Comment by tomashodek** [comment] 2023-06-14 15:07
Hope this is what you're looking for, it's the trigger of Generate UI and that resulting error mentioned. 

[idealog.txt](https://github.com/nrwl/nx-console/files/11747548/idealog.txt)

**Comment by tomashodek** [comment] 2023-06-14 15:35
Yes, CLI works just fine. I'll have a look. Is there a list of required config fields for `project.json` and `nx.json`? I think that would help a lot. 

Also, what you're saying, is that it can be caused by an app `project.json`? I was more looking into the general config files like `nx.json` or `tsconfig` maybe.

**Comment by MaxKless** [comment] 2023-06-14 15:44
Yes the `nx/workspace` LSP request also collects all the information on projects in your workspace. So something weird with the `project.json` file could screw things up here. 

Honestly the quickest way to find out what's happening would be the following:
- clone the nx-console repo
- add a console.log to the `apps/nxls/src/main.ts` file (see below)
- open nx console in webstorm and do `./gradlew runIde`
- open the repo in your locally built version of nx console and look at the log... then we can find out what's wrong with the workspace object

this is where the lsp handles an incoming `nx/workspace` request:
```
connection.onRequest(NxWorkspaceRequest, async ({ reset }) => {
  if (!WORKING_PATH) {
    return new ResponseError(1000, 'Unable to get Nx info: no workspace path');
  }

  return nxWorkspace(WORKING_PATH, lspLogger, reset);
});
```

**Comment by tomashodek** [comment] 2023-06-14 16:01
Ok cool, at least I know where to look. I'll try the repo asap and then post here the results. Thanks a lot.

**Comment by MaxKless** [comment] 2023-06-14 16:24
Thank you for helping with the debugging so much 🙏 good luck and let me know!

**Comment by localpcguy** [comment] 2023-06-19 18:13
Seeing what seems to be a similar issue. I have a blank Nx Console sidebar and cannot use the Nx Console "Nx Generate (UI)". I was able to use the Generate UI with previous versions of the plugin. I see both the same crash detailed above, and also this one (which seems like it could be similar (still not able to parse message) but maybe from a different action, like trying to access the Nx Console sidebar I believe).

```
2023-06-19 13:30:38,969 [  38726] SEVERE - #c.i.o.a.i.ActionUpdater - NxRunTargetActionGroup#getChildren@ProjectViewPopup (dev.nx.console.run.actions.NxRunTargetActionGroup), actionId=dev.nx.console.run.actions.NxRunTargetActionGroup, text='Nx: Run Target'
org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-19 13:30:38,972 [  38729] SEVERE - #c.i.o.a.i.ActionUpdater - PyCharm 2023.1  Build #PY-231.8109.197
2023-06-19 13:30:38,972 [  38729] SEVERE - #c.i.o.a.i.ActionUpdater - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-19 13:30:38,972 [  38729] SEVERE - #c.i.o.a.i.ActionUpdater - OS: Mac OS X
2023-06-19 13:30:38,973 [  38730] SEVERE - #c.i.o.a.i.ActionUpdater - Plugin to blame: Nx Console version: 1.6.1
2023-06-19 13:30:39,019 [  38776]   WARN - #c.i.o.a.i.Utils - 2678 ms to fillMenu@ProjectViewPopup
```

It'd be super helpful if there was a list of required/allowed parameters for the project.json file to be able to compare against. Not currently really setup (or have the time right now) to run the plugin right now, but if I do get a moment I'll try. In the meantime though, is there a file or page you can point to for looking at the project.json that gives the allowed keys?

**Comment by localpcguy** [comment] 2023-06-19 18:41
Follow-up - I think I found the problematic project.json file - in my UI lib, in the `targets` object, I had been using a glob for assets to reference assets in another library. Now that appears to be saying it is not allowed, and assets should be an array of strings (per the `node_modules/nx/schemas/project-schema.json` at least)?

We've been using this globbing pattern for some time now, and also use it in a couple of the apps in our mono-repo. It's based on this comment:
https://github.com/nrwl/nx/issues/88#issuecomment-516455824

```
{
  "name": "ui",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "prefix": "ui",
  "projectType": "library",
  "sourceRoot": "libs/ui/src",
  "tags": [],
  "targets": {
    "assets": [
      {
        "glob": "**/*",
        "input": "./libs/shared-assets",
        "output": "./assets/shared"
      }
    ],
    ...
```

I (temporarily) removed the 4 instances of globbing I had and restarted PyCharm, and both the Nx Console sidebar and the Nx Generate worked. 

However, I can't leave it like this, as I need those assets to be included during builds/deploys/etc. This has been working up to this point. So I do feel like this is a bug in Nx Console and/or the Project Schema pattern? Or is there another way this should be accomplished (short of having to hand-type out all of the files in our shared libs assets as strings instead of globs)?

**Comment by MaxKless** [comment] 2023-06-19 19:15
While the object might not be the way to do things anymore with the newest nx, it shouldn't break things either. 
I'll have a look at what we can do to improve the behaviour from the nx console side tomorrow :)

**Comment by localpcguy** [comment] 2023-06-19 22:58
Thanks! And I'm sure I can find it with a bit of digging, but if you have a resource or can point me in the right direction for the best way to do that in the latest version of Nx, that'd be awesome. It felt like a workaround even at the time, but we have a fair amount of assets that are shared between multiple libs/projects.

**Comment by MaxKless** [comment] 2023-06-20 06:18
Ok so I looked it over and I'm a bit confused. 
In the code sample you posted, it makes sense to me that it throws an error (and it does throw the error in my repro).
This creates an `asset` target that should have an object definition but instead is an array - that's not going to work either way. 
```
"targets": {
    "assets": [
      {
        "glob": "**/*",
        "input": "./libs/shared-assets",
        "output": "./assets/shared"
      }
    ]
```

The comment you linked has the assets array nested in a target's `options` which makes more sense to me. Is that how you did it too? Or did you actually use the code pasted above?

@tomashodek do you have something similar in your case?

**Comment by tomashodek** [comment] 2023-06-20 06:44
Hi, sorry, I'm busy this week, so I'll get to it in the next week and try to debug it once more.

**Comment by localpcguy** [comment] 2023-06-20 18:41
@MaxKless Doh - I grabbed the one example that was like that, you are correct, all of the others are nested in `options: { assets: [...] ... }`. I think maybe it was likely a copy/paste error and may not ever have worked. 🤦🏻 Like you said, it probably shouldn't break on a version update, but at least it is easily fixed. And, the other good news is, it did show as wrong in IntelliJ because it violates the project-schema.

![image](https://github.com/nrwl/nx-console/assets/593240/3076c525-8fcc-4a0c-9d68-fea5315b7170)

Removing that instance did not cause any issues (which would make sense since it probably wasn't doing anything to begin with). Thanks for your kindness in how you phrased your response!

**Comment by MaxKless** [comment] 2023-06-20 18:46
No problem and thanks for collaborating on fixing it!

**Comment by MaxKless** [comment] 2023-07-21 13:50
As you can see in the PR above, there will be a new action to analyze your nx config files (`project.json`, `nx.json`) in the next release!
So if you encounter this error, just run `Nx: Analyze Nx configuration files` to see where an error snuck in. Shouldn't be hard to fix because if the schema is wrong in a `project.json`, it's not picked up by Nx anyways. There is also an error notification telling you if this error occurs.

Closing this for now, let me know if anything else doesn't work.

**Closed by MaxKless** 2023-07-21 13:50 UTC
Labels: type: bug
