### ISSUE TITLE
Remote host process for @nrwl/angular:console unexpectedly exited 3 times in 5 minutes

### ISSUE THREAD

**Issue by xamelion** [nrwl/nx-console#2028] opened 2024-02-21 09:25 UTC
## Current Behavior

The remote host process for @nrwl/angular:console extension crashes repeatedly when opened in a devcontainer workspace in VSCode 1.74.2. This results in loss of console functionality.

## Expected Behavior 

The @nrwl/angular:console extension should initialize and work as expected in a devcontainer.

## Steps to Reproduce

1. Open devcontainer workspace in VSCode 1.74.2
2. Observe remote host process crashes for @nrwl/angular:console extension

## Failure Logs
2024-02-21 08:58:50.195 [info] ExtensionService#_doActivateExtension nrwl.angular-console, startup: false, activationEvent: 'onStartupFinished'
2024-02-21 08:58:51.455 [info] Extension host with pid 748 started

2024-02-21 08:58:51.455 [error] Error: EEXIST: file already exists, open '/home/node/.vscode-server/data/User/workspaceStorage/137f11bba6ad13a7c25ce94ec743f432/vscode.lock'
2024-02-21 08:58:51.460 [info] Lock '/home/node/.vscode-server/data/User/workspaceStorage/137f11bba6ad13a7c25ce94ec743f432/vscode.lock': Could not acquire lock, checking if the file is stale.
2024-02-21 08:58:51.463 [info] Lock '/home/node/.vscode-server/data/User/workspaceStorage/137f11bba6ad13a7c25ce94ec743f432/vscode.lock': The pid 360 appears to be gone.
2024-02-21 08:58:51.463 [info] Lock '/home/node/.vscode-server/data/User/workspaceStorage/137f11bba6ad13a7c25ce94ec743f432/vscode.lock': Deleting a stale lock.
2024-02-21 08:58:51.470 [info] Lock '/home/node/.vscode-server/data/User/workspaceStorage/137f11bba6ad13a7c25ce94ec743f432/vscode.lock': Lock acquired.
2024-02-21 12:12:23.100 [error] Error while registering log channel vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f78616d656c696f6e2f446f63756d656e74732f50524f4a454354532f6373676f66617374222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f78616d656c696f6e2f446f63756d656e74732f50524f4a454354532f6373676f666173742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f78616d656c696f6e2f446f63756d656e74732f50524f4a454354532f6373676f666173742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f78616d656c696f6e2f446f63756d656e74732f50524f4a454354532f6373676f666173742f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/node/.vscode-server/data/logs/20240221T085839/exthost2/vscode.github/GitHub.log Timed out while waiting for file to be created

## Environment

- Nx Console version: 18.16.0 (18.10.0 - worked)
- VSCode version: 1.74.2
- nx version: 14.4.3

**Comment by xamelion** [comment] 2024-02-21 09:47
The error occurs when using  "nrwl.angular-console" together   "esbenp.prettier-vscode"

**Comment by TheTiGuR** [comment] 2024-02-21 23:09
Revert to 18.10.1
See #1978

**Comment by MaxKless** [comment] 2024-02-26 11:41
Will close as duplicate of #1978

**Closed** 2024-03-25 11:04 UTC
Labels: type: bug
