### ISSUE TITLE
Targets based on project inference not showing in tasks list

### ISSUE THREAD

**Issue by maartencardinaels** [nrwl/nx-console#1289] opened 2022-06-01 06:33 UTC
## Current Behavior

With recent versions of Nx it is possible to [define a project target configurator to allow for project inference](https://nx.dev/extending-nx/project-inference-plugins). This works perfectly when using the command line. The issue however is that these tasks are not displayed anymore within the Nx console plugin.  

## Expected Behavior

Targets based on project inference should be visible too in the Nx console plugin.

## Steps to Reproduce

1. Have some project targets
2. Confirm they are visible within Nx console
3. Rewrite these targets by using project inference

### Failure Logs / Images / Videos

No logs available

### Environment

Windows 10 environment, Nx console version 0.44.0

 ```
 "devDependencies": {
    "@angular-devkit/architect": "^0.1303.6",
    "@angular-devkit/build-angular": "13.3.6",
    "@angular-eslint/eslint-plugin": "13.2.1",
    "@angular-eslint/eslint-plugin-template": "13.2.1",
    "@angular-eslint/template-parser": "13.2.1",
    "@angular/cli": "13.3.6",
    "@angular/compiler-cli": "13.3.9",
    "@angular/language-service": "13.3.9",
    "@azure/identity": "^2.0.4",
    "@azure/keyvault-secrets": "^4.4.0",
    "@compodoc/compodoc": "^1.1.18",
    "@cypress/code-coverage": "^3.9.12",
    "@istanbuljs/nyc-config-typescript": "^1.0.2",
    "@ngneat/eslint-plugin-reactive-forms": "^4.0.0",
    "@ngneat/spectator": "^10.0.1",
    "@nrwl/angular": "14.1.7",
    "@nrwl/cli": "14.1.7",
    "@nrwl/cypress": "14.1.7",
    "@nrwl/devkit": "14.1.7",
    "@nrwl/eslint-plugin-nx": "14.1.7",
    "@nrwl/jest": "14.1.7",
    "@nrwl/js": "14.1.7",
    "@nrwl/linter": "14.1.7",
    "@nrwl/node": "14.1.7",
    "@nrwl/nx-plugin": "14.1.7",
    "@nrwl/storybook": "14.1.7",
    "@nrwl/web": "14.1.7",
    "@nrwl/workspace": "14.1.7",
    "@storybook/addon-essentials": "~6.5.5",
    "@storybook/angular": "~6.5.5",
    "@storybook/builder-webpack5": "~6.5.5",
    "@storybook/manager-webpack5": "~6.5.5",
    "@tailwindcss/forms": "^0.5.2",
    "@twittwer/compodoc": "^1.8.0",
    "@types/jest": "27.5.1",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/node": "17.0.35",
    "@types/systemjs": "^6.1.1",
    "@typescript-eslint/eslint-plugin": "5.25.0",
    "@typescript-eslint/parser": "5.25.0",
    "azure-devops-node-api": "^11.1.1",
    "copy-webpack-plugin": "^11.0.0",
    "cross-env": "^7.0.2",
    "cypress": "9.6.1",
    "cypress-grep": "^2.13.1",
    "cypress-real-events": "1.7.0",
    "cypress-terminal-report": "3.5.2",
    "del": "^6.1.0",
    "dotenv": "16.0.1",
    "eslint": "8.16.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-mocha": "10.0.4",
    "eslint-plugin-rxjs": "5.0.2",
    "glob": "^8.0.3",
    "husky": "8.0.1",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jest": "27.5.1",
    "jest-extended": "0.11.5",
    "jest-junit": "13.2.0",
    "jest-preset-angular": "11.1.2",
    "lint-staged": ">=12.4.1",
    "mini-css-extract-plugin": "^2.6.0",
    "nx": "14.1.7",
    "nx-remotecache-azure": "1.1.0",
    "orval": "6.6.4",
    "patch-package": "^6.4.7",
    "postcss": "8.4.14",
    "prettier": "2.6.2",
    "rxjs-spy": "^8.0.2",
    "source-map-loader": "^3.0.1",
    "style-loader": "^3.3.1",
    "svg-to-ts": "8.6.1",
    "tailwindcss": "^3.0.24",
    "terser-webpack-plugin": "^5.3.1",
    "ts-jest": "27.1.4",
    "ts-node": "10.8.0",
    "tslib": "^2.4.0",
    "typescript": "4.6.4",
    "webpack": "^5.72.1",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-config-single-spa": "^5.2.0",
    "webpack-dev-server": "4.8.1",
    "webpack-merge": "^5.8.0",
    "webpack-node-externals": "^3.0.0",
    "webpack-sources": "^3.2.3"
  }
```

**Comment by Cammisuli** [comment] 2022-06-01 15:23
Just to confirm.. Are you really using Nx Console 0.44.0?

Otherwise, since we're using the Nx utilities to get all the projects and targets it'll most likely have to be fixed in Nx core. Do you have a reproducible repo that I can take a look at?

**Comment by Cammisuli** [comment] 2022-06-01 20:58
I looked into this some more, and there's a way to make sure that we get the right information using the project graph. I'll find a way to get this implemented 😄

**Closed** 2022-06-03 20:47 UTC
Labels: type: bug
